Add user model
The7Fame/trainee-planner pull request #11
Opened 2023-08-10 09:29 UTC by The7Fame

2023-08-14 04:38 UTC, TimurShakhlai requested changes

2023-08-14 04:38 UTC, TimurShakhlai commented on spec/factories/users.rb
не лучше ли заполнять поля с помощью Faker?

2023-08-14 06:06 UTC, The7Fame commented on spec/factories/users.rb
Добавил.

2023-08-15 06:57 UTC, TimurShakhlai approved these changes

2023-08-15 07:01 UTC, TimurShakhlai reviewed
а где Сиды для юзера?

2023-08-15 07:13 UTC, The7Fame commented
> а где Сиды для юзера?

Не добавлял, так как создал юзера через UI. Посчитал , что одной юзера будете достаточно и из-за не делал сиды.

2023-08-15 09:06 UTC, The7Fame commented
> > а где Сиды для юзера?
> 
> Не добавлял, так как создал юзера через UI. Посчитал , что одной юзера будете достаточно и из-за не делал сиды.

Добавил сиды для пользователя

2023-08-16 11:01 UTC, TsikhanauDzmitry requested changes

2023-08-16 11:01 UTC, TsikhanauDzmitry commented on db/migrate/20230811140506_devise_create_users.rb
> +      # t.datetime :locked_at
Зачем это в файле?

2023-08-16 11:01 UTC, TsikhanauDzmitry commented on db/migrate/20230811140552_add_first_name_last_name_to_users.rb
Почему для этого отдельная миграция? Не логично ли в создании пользователя добавить эти поля?

2023-08-16 11:01 UTC, TsikhanauDzmitry commented on db/migrate/20230811140506_devise_create_users.rb
> +    # add_index :users, :unlock_token,         unique: true
А это зачем тут?

2023-08-16 11:01 UTC, TsikhanauDzmitry commented on db/seeds.rb
Тут я вижу сразу несколько проблем:

1. При повторном запуске сидов они сломаются, потому что email - уникальное поле, а эти пользователи уже будут в БД
2. Согласись, что `5.times do |i| i += 1` выглядит не серьезно
3. Я говорил, что очень важное условие - сиды только для dev окружения

2023-08-16 13:10 UTC, The7Fame commented on db/migrate/20230811140506_devise_create_users.rb
> +      # t.datetime :locked_at
Это генерирует devise при создании User.
Я это не использую, это для расширения модели, чтобы можно было отслеживать, просить подтверждение по почте, блокировать, если количество попыток превышены. Удалю, чтобы не загромождать файл.

2023-08-16 13:10 UTC, The7Fame commented on db/migrate/20230811140506_devise_create_users.rb
> +    # add_index :users, :unlock_token,         unique: true
Это генерирует devise при создании User.
Я это не использую, удалю, чтобы не загромождать файл.

2023-08-16 13:11 UTC, The7Fame commented on db/migrate/20230811140552_add_first_name_last_name_to_users.rb
Так сделал, потому то rubocop ругается на превышенное количество строк в методе 12/10.
Поэтому решил сделать отдельно создание колонок `first_name` и `last_name` в таблице `users`

2023-08-17 13:31 UTC, The7Fame commented on db/seeds.rb
Исправил

2023-08-17 13:40 UTC, TimurShakhlai approved these changes

2023-08-21 16:12 UTC, TimurShakhlai approved these changes

2023-08-22 07:12 UTC, TsikhanauDzmitry requested changes

2023-08-22 07:12 UTC, TsikhanauDzmitry commented on db/migrate/20230811140552_add_first_name_last_name_to_users.rb
> +    change_table :users, bulk: true do |t|
Зачем тут `bulk: true`?

2023-08-22 07:12 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +    first_name: "User#{index + 1}",
Имя лучше задавать с помощью Faker

2023-08-22 07:12 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +    password: "password#{index + 1}"
Для пароля достаточно у всех одного слова `password`

2023-08-22 07:12 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +    email: "test#{index + 1}@test.com",
Почему test? Думаю, что лучшее решение: `user_#{i}@example.com`. Так мы будем точно знать, что это пользователь, а также по домену будет понятно, что это сделано сидами

2023-08-22 07:12 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    email { Faker::Internet.email }
Думаю, что можно было бы указать, что email - уникальное поле. Что думаешь?

2023-08-22 11:34 UTC, The7Fame commented on db/seeds/development.rb
> +    first_name: "User#{index + 1}",
Исправил

2023-08-22 11:34 UTC, The7Fame commented on db/seeds/development.rb
> +    password: "password#{index + 1}"
Исправил

2023-08-22 11:34 UTC, The7Fame commented on db/seeds/development.rb
> +    email: "test#{index + 1}@test.com",
Исправил

2023-08-22 11:34 UTC, The7Fame commented on spec/factories/users.rb
> +    email { Faker::Internet.email }
Соглашусь, исправил

2023-08-22 11:34 UTC, The7Fame commented on db/migrate/20230811140552_add_first_name_last_name_to_users.rb
> +    change_table :users, bulk: true do |t|
Объединяет два запроса в один SQL-запрос.

2023-08-22 12:03 UTC, TimurShakhlai approved these changes

2023-08-24 08:30 UTC, TimurShakhlai approved these changes

2023-08-24 09:41 UTC, TsikhanauDzmitry requested changes

2023-08-24 09:41 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Фамилия - это же не обязательное поле. Может сделать отдельный trait для пользователя с фамилией?

2023-08-24 10:01 UTC, The7Fame commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Исправил, вынес фамилию в trait.

2023-08-25 08:56 UTC, TimurShakhlai approved these changes

2023-08-25 09:23 UTC, TsikhanauDzmitry approved these changes

2023-08-25 09:36 UTC, TsikhanauDzmitry requested changes

2023-08-25 09:36 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    trait :last_name do
Не совсем правильное название у трейта

2023-08-25 09:50 UTC, The7Fame commented on spec/factories/users.rb
> +    trait :last_name do
Изменил название

2023-08-25 11:37 UTC, TimurShakhlai approved these changes

2023-08-28 10:45 UTC, TimurShakhlai approved these changes

2023-08-28 13:33 UTC, TsikhanauDzmitry requested changes

2023-08-28 13:33 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +    let(:user) { build(:user, :with_last_name) }
Я бы дал красноречивое имя для данной переменной

2023-08-28 13:33 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +  describe 'user with last_name' do
Думаю можно этот describe назвать так, чтобы было понятно, что именно ты проверяешь. Типа `traits`. А потом уже внутрь покласть данный describe

2023-08-29 03:54 UTC, The7Fame commented on spec/models/user_spec.rb
> +  describe 'user with last_name' do
Сделано

2023-08-29 08:43 UTC, TsikhanauDzmitry approved these changes

2023-08-29 12:38 UTC, merged