generate views
The7Fame/trainee-planner pull request #13
Opened 2023-08-10 09:55 UTC by The7Fame

2023-08-21 16:16 UTC, TimurShakhlai commented on app/controllers/users/registrations_controller.rb
наверное надо почистить файл исходя из 11 пр

2023-08-22 05:42 UTC, The7Fame commented on app/controllers/users/registrations_controller.rb
Исправил

2023-08-22 06:21 UTC, TimurShakhlai approved these changes

2023-08-23 06:43 UTC, TimurShakhlai approved these changes

2023-08-24 08:33 UTC, TimurShakhlai approved these changes

2023-08-24 09:45 UTC, TsikhanauDzmitry requested changes

2023-08-24 09:45 UTC, TsikhanauDzmitry commented on app/assets/stylesheets/application.scss
> +}
Такого не должно быть в этом файле. Рекомендую делать отдельные scss файлы для добавления новых стилей.

2023-08-24 09:45 UTC, TsikhanauDzmitry commented on app/controllers/users/registrations_controller.rb
> +    protected
Почему тут protected?

2023-08-24 09:45 UTC, TsikhanauDzmitry commented on app/helpers/home_helper.rb
Зачем этот файл?

2023-08-29 13:02 UTC, The7Fame commented on app/assets/stylesheets/application.scss
> +}
Добавил в отдельный файл style.scss

2023-08-29 13:02 UTC, The7Fame commented on app/helpers/home_helper.rb
Данный файл создаётся автоматически во время генерации контроллера.
В данный файл можно положить методы, которые будут использоваться на уровне views.
Удалил этот файл, так как он не используется.

2023-08-29 13:05 UTC, The7Fame commented on app/controllers/users/registrations_controller.rb
> +    protected
`Protected` ограничивает доступ и видимость метода для самого контроллера и его подклассов(они могут использовать данный метод). Заменил на `private`, так так подклассы данного класса в последующем не понадобятся.

2023-09-06 14:57 UTC, TsikhanauDzmitry requested changes

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
Не правильное название файла. Лучше будет: `app/views/users/partials/login.html.erb`

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
> +    <a class="nav-link" href="#" ><%=t ('nav.events') %></a>
Вечные проблемы с пробелами перед `t`

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
> +  </li>
Зачем это было добавлено, если этой логики еще нет?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
> +  <%= button_to t('user.sign_out'), destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
Давай сделаем вот такой дропдаун:
![Screenshot from 2023-09-06 17-41-11](https://github.com/The7Fame/trainee-planner/assets/114392328/af8e8874-2e11-4d3c-8a10-5897390d761a)

Profile - это страница с изменением пользователя, а также его аватарки
Sign Out - это собственно выход

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
Это на всех языках работает?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
> +    <%= f.label :email %><br />
Что за тэг `<br />`?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
Это касается всех строк в файле

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
Как выглядит данная страница?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/mailer/confirmation_instructions.html.erb
Что с поддержкой языков? Как выглядит данный email?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/mailer/confirmation_instructions.html.erb
Это касается всех имейлов

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/shared/_flash_notice.html.erb
Код с названием файла вообще не состыкается

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on app/views/users/shared/_links.html.erb
Этот файл обязательно должен быть?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on config/initializers/devise.rb
> +  config.scoped_views = true
Зачем это было изменено?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on config/routes.rb
> +    devise_for :users, controllers: { registrations: 'users/registrations' }
Менялась только регистрация?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on config/routes.rb
> +    devise_for :users, controllers: { registrations: 'users/registrations' }
Не думаю, что красиво root переносить вниз. Давай держать корень вверху все-таки

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on my/locales/ru.yml
Мне кажется, что тут большое всего, в отличии от `en` версии. Почему так?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> +  describe 'GET ' do
Интересное название

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
>      end
А как вообще этот тест работает? Ты же даже не переходишь на index страницу

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> +      end
А как вообще этот тест работает? Ты же даже не переходишь на index страницу

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> -      expect(response).to render_template('index')
Почему этот тест был удален?

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> +      end
Я каждый раз повторяю, что при наличии 1 строки в бефор блоке мы пишем через `{ }`

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/features/user_spec.rb
Это view тесты. В фича тестах мы проверяем то, что будет, когда он заполнит эти поля и нажмет кнопку

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/features/user_spec.rb
Также все эти тесты нужно разделить:
* `spec/features/users/sign_in_spec.rb`
* `spec/features/users/sign_up_spec.rb`
* `spec/features/users/edit_profile_spec.rb`

2023-09-06 14:57 UTC, TsikhanauDzmitry commented on spec/routings/home_routing_spec.rb
> +  end
Это вообще никак не относится к `home_routing`

2023-09-07 01:42 UTC, TimurShakhlai approved these changes

2023-09-08 05:43 UTC, The7Fame commented on app/views/layouts/_user-login.html.erb
> +    <a class="nav-link" href="#" ><%=t ('nav.events') %></a>
Исправлено

2023-09-08 05:43 UTC, The7Fame commented on app/views/layouts/_user-login.html.erb
> +  </li>
Удалил

2023-09-08 05:43 UTC, The7Fame commented on app/views/layouts/_user-login.html.erb
> +  <%= button_to t('user.sign_out'), destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
Добавил

2023-09-08 05:43 UTC, The7Fame commented on app/views/users/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
Сделал перевод

2023-09-08 05:43 UTC, The7Fame commented on spec/controllers/home_controller_spec.rb
> -      expect(response).to render_template('index')
Случайно, добавил его обратно

2023-09-08 05:44 UTC, The7Fame commented on spec/features/user_spec.rb
Исправлено

2023-09-08 05:44 UTC, The7Fame commented on spec/features/user_spec.rb
Сделано

2023-09-08 05:44 UTC, The7Fame commented on spec/routings/home_routing_spec.rb
> +  end
Вынес в отдельный файл

2023-09-08 05:54 UTC, The7Fame commented on config/initializers/devise.rb
> +  config.scoped_views = true
Чтобы devise искал сгенерированные представления в папке users.

2023-09-08 07:45 UTC, TimurShakhlai approved these changes

2023-09-08 08:41 UTC, The7Fame commented on app/views/layouts/_user-login.html.erb
Исправил

2023-09-08 08:44 UTC, The7Fame commented on app/views/users/confirmations/new.html.erb
Вот так она выглядит.

![resend](https://user-images.githubusercontent.com/96648793/266542158-63e790b0-4b69-42d4-8a68-80a93283d645.jpg)

2023-09-11 14:15 UTC, TsikhanauDzmitry requested changes

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/layouts/_flash_success.html.erb
Думаю, что все виды флеш-сообщений можно объеденить. Посмотри общаю часть данных сообщений и попробуй объеденить

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +    <% unless user_signed_in?%>
Очень не любишь ты пробелы ставить

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +    <% end %>
Очень странная реализация if-else блока...

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +    <% end %>
Насколько я помню, достаточно проверять `current_user`

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +<%= render partial: 'layouts/flash_success' %>
Это не должно быть в хэдере. Лучше в аплик добавлять

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
Думаю, что красивее будет в центре. Как считаешь?

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
А также покажи мне скрин с русским языком, пожалуйста

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on spec/features/home/home_spec.rb
Может лучше: `spec/features/home/index_spec.rb`?

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on spec/features/users/edit_profile_spec.rb
А где кейсы с некорректным вводом?

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on spec/features/users/sign_in_spec.rb
А где кейсы с некорректным вводом?

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on spec/features/users/sign_up_spec.rb
А где кейсы с некорректным вводом?

2023-09-11 14:15 UTC, TsikhanauDzmitry commented on spec/routings/users_routing_spec.rb
> +    expect(get('/users/sign_up')).to route_to(controller: 'users/registrations', action: 'new')
А давай сделаем пути проще? Типа `/login`, `/sign_out` и `/sign_up`

2023-09-12 05:36 UTC, The7Fame commented on app/views/layouts/_flash_success.html.erb
Сделано.

2023-09-12 05:37 UTC, The7Fame commented on app/views/layouts/_header.html.erb
> +    <% unless user_signed_in?%>
Добавлен.

2023-09-12 05:37 UTC, The7Fame commented on app/views/layouts/_header.html.erb
> +    <% end %>
Переписал.

2023-09-12 05:37 UTC, The7Fame commented on app/views/layouts/_header.html.erb
> +    <% end %>
Сделал с `current_user`.

2023-09-12 05:37 UTC, The7Fame commented on app/views/layouts/_header.html.erb
> +<%= render partial: 'layouts/flash_success' %>
Добавил.

2023-09-12 05:38 UTC, The7Fame commented on spec/features/home/home_spec.rb
Да, так будет лучше, исправил.

2023-09-12 05:38 UTC, The7Fame commented on spec/features/users/edit_profile_spec.rb
Добавил.

2023-09-12 05:38 UTC, The7Fame commented on spec/features/users/sign_in_spec.rb
Добавил.

2023-09-12 05:38 UTC, The7Fame commented on spec/features/users/sign_up_spec.rb
Добавил.

2023-09-12 05:38 UTC, The7Fame commented on spec/routings/users_routing_spec.rb
> +    expect(get('/users/sign_up')).to route_to(controller: 'users/registrations', action: 'new')
Сделано.

2023-09-12 07:43 UTC, TimurShakhlai approved these changes

2023-09-12 08:44 UTC, TsikhanauDzmitry requested changes

2023-09-12 08:44 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
@The7Fame я тут ответа не получил

2023-09-12 08:44 UTC, TsikhanauDzmitry commented on app/views/users/mailer/confirmation_instructions.html.erb
Мне не нравится, что тут все на английском. Имейлы приходят только на этом языке?

2023-09-12 08:44 UTC, TsikhanauDzmitry commented on app/views/users/partials/_login.html.erb
> +    <li><%= button_to t('user.sign_out'), destroy_user_session_path, :method=>'delete', class: "dropdown-item btn btn-danger" %></li>
`:method=>'delete'` - уверен?

2023-09-12 12:03 UTC, The7Fame commented on app/views/users/confirmations/new.html.erb
Да, в центре будет красивее и поместил в бордер.

- en 

![resend_en](https://github.com/The7Fame/trainee-planner/assets/96648793/1fb6ead1-1d65-4ebf-b7b6-45dfc0628723)

- ru

![resend_ru](https://github.com/The7Fame/trainee-planner/assets/96648793/f475782e-51c0-44ec-973d-69e72326f450)

2023-09-12 12:06 UTC, The7Fame commented on app/views/users/partials/_login.html.erb
> +    <li><%= button_to t('user.sign_out'), destroy_user_session_path, :method=>'delete', class: "dropdown-item btn btn-danger" %></li>
Да, но переписал как 'method: :delete', но и с изначальной версией тоже работало.

2023-09-12 14:07 UTC, TimurShakhlai approved these changes

2023-09-13 07:38 UTC, The7Fame commented on app/views/users/mailer/confirmation_instructions.html.erb
На русском тоже приъодят

2023-09-13 07:40 UTC, TsikhanauDzmitry requested changes

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/mailer/email_changed.html.erb
Тут на разных языках?

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/mailer/password_change.html.erb
Тут на разных языках?

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/mailer/reset_password_instructions.html.erb
Тут на разных языках?

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/mailer/unlock_instructions.html.erb
Тут на разных языках?

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/partials/_login.html.erb
Не совсем согласен с названием файла. Это же user_dropdown так-то. Думаю такое и должно быть название

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
> +            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control mx-auto", placeholder: t('user.email'), value: (resource.pending_reconfirmation? ? resource.unconfir
Какая длина у данной строчки? Она проходит по стайл гайду в ограничении 120 символов?

2023-09-13 07:40 UTC, TsikhanauDzmitry commented on app/views/users/confirmations/new.html.erb
> +            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control mx-auto", placeholder: t('user.email'), value: (resource.pending_reconfirmation? ? resource.unconfir
Так же проверь все остальные файлы, чтобы длина строк соблюдалась

2023-09-13 09:43 UTC, The7Fame commented on app/views/users/partials/_login.html.erb
Изменил

2023-09-13 09:43 UTC, The7Fame commented on app/views/users/mailer/unlock_instructions.html.erb
Добавил.

2023-09-13 09:43 UTC, The7Fame commented on app/views/users/mailer/reset_password_instructions.html.erb
Добавил.

2023-09-13 09:43 UTC, The7Fame commented on app/views/users/mailer/password_change.html.erb
Добавил.

2023-09-13 09:43 UTC, The7Fame commented on app/views/users/mailer/email_changed.html.erb
Добавил.

2023-09-13 12:07 UTC, The7Fame commented on app/views/users/confirmations/new.html.erb
> +            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control mx-auto", placeholder: t('user.email'), value: (resource.pending_reconfirmation? ? resource.unconfir
Проверил, изменил.

2023-09-13 12:27 UTC, TimurShakhlai approved these changes

2023-09-13 13:49 UTC, TsikhanauDzmitry approved these changes

2023-09-13 13:50 UTC, TsikhanauDzmitry commented on app/views/users/partials/_login.html.erb
> +    <li><%= button_to t('user.sign_out'), destroy_user_session_path, :method=>'delete', class: "dropdown-item btn btn-danger" %></li>
@The7Fame оно работало, но это старая реализация

2023-09-13 13:53 UTC, merged