Add model Category and make seeds
The7Fame/trainee-planner pull request #14
Opened 2023-08-11 09:28 UTC by The7Fame

2023-08-14 04:46 UTC, TimurShakhlai requested changes
то же замечание про Faker

2023-08-14 06:05 UTC, The7Fame commented
> то же замечание про Faker

Добавил.

2023-08-15 07:04 UTC, TimurShakhlai requested changes

2023-08-15 07:04 UTC, TimurShakhlai commented on db/seeds.rb
> +categories = %w[Личное Работа Отдых]
тут наверное тоже Факер поможет

2023-08-15 07:05 UTC, The7Fame commented on db/seeds.rb
> +categories = %w[Личное Работа Отдых]
согласное ТЗ категории должны быть предопределены
<img width="460" alt="image" src="https://github.com/The7Fame/trainee-planner/assets/96648793/042b4d21-7447-42f2-aa71-df0b3a892c1d">

2023-08-15 14:48 UTC, TimurShakhlai approved these changes

2023-08-17 12:52 UTC, TimurShakhlai approved these changes

2023-08-18 07:54 UTC, TsikhanauDzmitry requested changes

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on db/seeds.rb
> +load(Rails.root.join('db', 'seeds', "#{Rails.env.downcase}.rb"))
Так лучше не делать. В этом случае не понятно, что будет, если сиды запустят на энве не девелоп.

Думаю, что лучше было бы просто в начало добавить проверку энвайромента.

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +Category.destroy_all
Плохая практика. У рельсов есть очень классные модификации метода create. Вот тут есть различные вариации использования метода create https://edgeapi.rubyonrails.org/classes/ActiveRecord/Relation.html

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +categories.each do |category|
Ввести переменную - хорошая идея, но в данном случае было бы достаточно 
`
%w[Личное Работа Отдых].each do |category|
`

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +  Category.create!(name: category)
Думаю, что в приницпе весь этот блок можно написать в строчку. Как считаешь?

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +categories = %w[Личное Работа Отдых]
Не принятно в целом использование русских слов в БД... Вдруг твое приложение будут смотреть иностранцы?

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on spec/factories/categories.rb
> +    name { Faker::Lorem.character }
Судя по сидам у тебя всего 3 категории. Если это так, то не думаю, что использование факера - правильное решение

2023-08-18 07:54 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
Попробуй переписать данные тесты

2023-08-18 08:18 UTC, The7Fame commented on db/seeds/development.rb
> +Category.destroy_all
Исправил

2023-08-18 08:19 UTC, The7Fame commented on db/seeds/development.rb
> +categories.each do |category|
Исправил

2023-08-18 08:19 UTC, The7Fame commented on db/seeds/development.rb
> +  Category.create!(name: category)
Переписал в одну строчку.

2023-08-18 08:19 UTC, The7Fame commented on db/seeds/development.rb
> +categories = %w[Личное Работа Отдых]
Исправил

2023-08-18 08:20 UTC, The7Fame commented on db/seeds.rb
> +load(Rails.root.join('db', 'seeds', "#{Rails.env.downcase}.rb"))
Добавил проверку

2023-08-18 11:38 UTC, The7Fame commented on spec/models/category_spec.rb
Переписал

2023-08-18 11:39 UTC, The7Fame commented on spec/factories/categories.rb
> +    name { Faker::Lorem.character }
Немного не понимаю. Тут Faker создаёт Category, чтобы можно было манипулировать в тестах.

2023-08-21 16:19 UTC, TimurShakhlai approved these changes

2023-08-24 08:51 UTC, TimurShakhlai approved these changes

2023-08-25 08:58 UTC, TimurShakhlai approved these changes

2023-08-25 09:29 UTC, TsikhanauDzmitry requested changes

2023-08-25 09:29 UTC, TsikhanauDzmitry commented on spec/factories/categories.rb
> +    name { Faker::Lorem.character }
Смотри, если у тебя всего 3 категории, то есть несколько путей решения проблемы:
1. Сделать 3 разных фактори, где каждая отвечает за одно состояние
2. Сделать рандомную выборку из категорий, а потом добавить трейты

2023-08-25 09:29 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
Я бы добавил тесты, которые проверяют все возсожные названия категорий

2023-08-28 10:47 UTC, TimurShakhlai approved these changes

2023-08-28 13:36 UTC, TsikhanauDzmitry requested changes

2023-08-28 13:36 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
> +  subject(:category) { build :category }
Советую все-таки параметры методов указывать в скобочках

2023-08-28 13:36 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
> +  describe 'categories' do
Название должно быть более четкое

2023-08-28 13:36 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
> +    context 'when category :vacation' do
Думаю принцип имени тут должен быть типа: `"when name of category is 'Vacation'"`

2023-08-29 03:54 UTC, The7Fame commented on spec/models/category_spec.rb
> +  subject(:category) { build :category }
Сделано

2023-08-29 03:54 UTC, The7Fame commented on spec/models/category_spec.rb
> +  describe 'categories' do
Исправлено

2023-08-29 03:54 UTC, The7Fame commented on spec/models/category_spec.rb
> +    context 'when category :vacation' do
Исправлено

2023-08-29 08:47 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
> +    context 'when category :vacation' do
Это не было исправленно, как я попросил(

2023-08-29 08:55 UTC, The7Fame commented on spec/models/category_spec.rb
> +    context 'when category :vacation' do
То есть весь этот кусок должен быть не таким, как ниже я исправил , верно понимаю?

```
describe 'traits' do
    context "when category 'Vacation'" do
      let(:category_vacation) { build(:category, :vacation) }

      it { expect(category_vacation.name).to eql 'Vacation' }
    end

    context "when category 'Personal'" do
      let(:category_personal) { build(:category, :personal) }

      it { expect(category_personal.name).to eql 'Personal' }
    end

    context "when category 'Work'" do
      let(:category_work) { build(:category, :work) }

      it { expect(category_work.name).to eql 'Work' }
    end
 end
```

2023-08-30 07:49 UTC, TsikhanauDzmitry approved these changes

2023-08-30 08:14 UTC, merged