Category controllers views
The7Fame/trainee-planner pull request #15
Opened 2023-08-13 06:11 UTC by The7Fame

2023-08-21 16:20 UTC, TimurShakhlai approved these changes

2023-08-22 12:04 UTC, TimurShakhlai approved these changes

2023-08-24 08:53 UTC, TimurShakhlai approved these changes

2023-09-11 14:24 UTC, TsikhanauDzmitry requested changes

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
Есть ли какие-нибудь ограничения для не авторизованных пользователей?

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @category = Category.create(category_params)
Уверен, что тут правильный метод?

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +      redirect_to categories_path
Это можно написать в одной строке

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
У нас нет show метода?

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +  end
Всегда ли у нас будет удаление без ошибок?

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    redirect_to categories_path
Это можно написать в одной строке

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    params.require(:category).permit(:name)
Расскажи пожалуйста, зачем это было реализованно?

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/views/categories/_categories.html.erb
> +      </tr>
Такое лучше в отдельный partial вынести

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/views/categories/_error.html.erb
Не думаю, что правильным решением будет для каждого контроллера выносить отдельный вывод ошибок

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/views/categories/_categories.html.erb
> +    <tr style="text-align: center">
Нельзя в самом коде указывать стили. Мы используем классовую систему для стилей. Если хочешь, то пиши кастомные css-классы

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/views/categories/_categories.html.erb
> +    <tr style="text-align: center">
Это касается и кода далее

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on app/views/categories/new.html.erb
> +    <%= render partial: 'categories/form',  locals: { category: @category }%>
Кажется, что тут прячутся лишние пробелы

2023-09-11 14:24 UTC, TsikhanauDzmitry commented on spec/controllers/categories_controller_spec.rb
> +  end
Уже по данному тесту вижу, что писалось без методички. Далее проверять пока не буду

2023-09-13 15:28 UTC, TimurShakhlai approved these changes

2023-09-14 07:16 UTC, The7Fame commented on app/controllers/categories_controller.rb
Добавил.

2023-09-14 07:16 UTC, The7Fame commented on app/controllers/categories_controller.rb
Добавил.

2023-09-14 07:16 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +    @category = Category.create(category_params)
Да, категория создаётся.

2023-09-14 07:16 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +    params.require(:category).permit(:name)
Добавлено для того, что можно было обновлять или создавать. В require модель, permit - поля.

2023-09-14 07:16 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +      redirect_to categories_path
Исправил

2023-09-14 07:17 UTC, The7Fame commented on spec/controllers/categories_controller_spec.rb
> +  end
Переписал.

2023-09-14 08:28 UTC, The7Fame commented on app/views/categories/_categories.html.erb
> +      </tr>
Вынес

2023-09-14 08:28 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +  end
Исправил

2023-09-14 08:29 UTC, The7Fame commented on app/views/categories/new.html.erb
> +    <%= render partial: 'categories/form',  locals: { category: @category }%>
Убрал

2023-09-14 08:29 UTC, The7Fame commented on app/views/categories/_categories.html.erb
> +    <tr style="text-align: center">
Исправлено.

2023-09-14 08:34 UTC, TsikhanauDzmitry requested changes

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/assets/stylesheets/application.scss
> +@import 'style';
Пустые строчки в конце файла должны быть

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/assets/stylesheets/style.scss
> +}
Пустые строчки в конце файла должны быть

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/assets/stylesheets/style.scss
> +}
Если это стили только для ошибок, то я бы вынес их в отдельный файл, где будут храниться стили именно ошибок. CSS - это ООП язык (если его можно так назвать), потому файловая ситсема почти как классовая работает

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @category = Category.create(category_params)
@The7Fame  Ты не правильно понял. `create` метод содержит в себе `save`. Думаю, что сначала мы должны инициализировать, а потом сохранять

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
У тебя во многих местах повторяется следующий код:
```
@category = Category.find(params[:id])
```

Я бы рекомендовал, согласно принципу **DRY** вынести это в общий метод, который вызывается в коллбэке для определенных экшонов. Как смотришь на такое?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/views/categories/partials/_category.html.erb
> +
Пустая строчка?)

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on app/views/layouts/_flash_msg.html.erb
Разве мы уже не замержили что-то похожее?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on spec/controllers/categories/categories_controller_delete_spec.rb
> +  end
Думаю, что эти контексты должны быть в describe блоках, а не отдельно

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on spec/controllers/categories/categories_controller_edit_spec.rb
> +    context 'when user is not authenticated create category' do
Некорректное имя

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on spec/controllers/categories/categories_controller_show_spec.rb
> +      end
Почему бы не вынести `show_category` в отдельный `before`?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on spec/controllers/home/home_controller_spec.rb
Может лучше `spec/controllers/home/home_controller_index_spec.rb`?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on spec/features/categories/category_create_spec.rb
А где исход, с ошибкой (имя занято)?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on spec/routings/categories_routing_spec.rb
А где `show` и `create`?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on config/routes.rb
> +    devise_for :users, path: ''
А почему роуты для девайса поменялись? Ты точно сделал правильный rebase?

2023-09-14 08:34 UTC, TsikhanauDzmitry commented on config/routes.rb
> +    resources :categories
Получается, что каждый пользователь может удалять, изменять и т.п. категории других людей. Правильно ли это?

2023-09-14 08:35 UTC, The7Fame commented on app/views/categories/_error.html.erb
Да, сделал.

2023-09-14 09:13 UTC, The7Fame commented on app/views/categories/_categories.html.erb
> +      </tr>
Вынес

2023-09-14 09:13 UTC, The7Fame commented on app/views/categories/_error.html.erb
Исправил

2023-09-14 09:14 UTC, The7Fame commented on app/views/categories/_categories.html.erb
> +    <tr style="text-align: center">
Исправил

2023-09-14 09:15 UTC, The7Fame commented on app/assets/stylesheets/style.scss
> +}
Переименовал как `error`.

2023-09-14 09:15 UTC, The7Fame commented on app/assets/stylesheets/style.scss
> +}
Добавил

2023-09-14 09:17 UTC, The7Fame commented on spec/controllers/home/home_controller_spec.rb
Исправил

2023-09-14 09:23 UTC, The7Fame commented on spec/features/categories/category_create_spec.rb
Добавил

2023-09-14 09:26 UTC, The7Fame commented on spec/routings/categories_routing_spec.rb
Добавил `show`, исправил `new ` на `create`.

2023-09-14 09:27 UTC, TimurShakhlai approved these changes

2023-09-14 09:44 UTC, The7Fame commented on app/assets/stylesheets/application.scss
> +@import 'style';
Добавил

2023-09-14 09:57 UTC, The7Fame commented on app/controllers/categories_controller.rb
Вынес в `before_action :set_category, only: %i[show edit update destroy]`.

2023-09-15 17:37 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +    @category = Category.create(category_params)
Исправил

2023-09-15 17:38 UTC, The7Fame commented on config/routes.rb
> +    devise_for :users, path: ''
Теперь всё верно

2023-09-15 17:38 UTC, The7Fame commented on config/routes.rb
> +    resources :categories
Это не есть правильно. Исправил.

2023-09-15 17:42 UTC, The7Fame commented on spec/controllers/categories/categories_controller_edit_spec.rb
> +    context 'when user is not authenticated create category' do
Исправил

2023-09-15 17:42 UTC, The7Fame commented on spec/controllers/categories/categories_controller_show_spec.rb
> +      end
Вынес

2023-09-15 17:50 UTC, The7Fame commented on app/views/categories/partials/_category.html.erb
> +
Убрал)

2023-09-18 06:58 UTC, TsikhanauDzmitry requested changes
Дальше миграции не проверял, потому что еще в контроллере есть моменты для исправления + #29 должен быть исправлен еще раньше

2023-09-18 06:58 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @categories = Category.all
Пагинацию не добавлял?

2023-09-18 06:58 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +  end
Очень не люблю такие каскадные `if` блоки. Лучше попробуй красиво реализовать через `return`

2023-09-18 06:58 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +      current_user.categories << @category
Это выглядит очень не правильно

2023-09-18 06:58 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +        redirect_to category_path(@category)
Нельзя тут в одну строчку написать?

2023-09-18 06:58 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +      current_user.categories.delete(@category)
У нас тут очень много запросов в БД. Тебе так не кажется?

2023-09-20 06:08 UTC, TimurShakhlai approved these changes

2023-09-20 15:04 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +      current_user.categories << @category
Вынес в сервис

2023-09-20 15:04 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +        redirect_to category_path(@category)
Исправил

2023-09-20 15:04 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +      current_user.categories.delete(@category)
Исправил

2023-09-20 18:05 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +    @categories = Category.all
Добавил

2023-09-20 18:05 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +  end
Изменил

2023-09-21 05:59 UTC, TimurShakhlai approved these changes

2023-09-21 06:50 UTC, TsikhanauDzmitry requested changes
Тесты не смотрел, думаю, что проблемы, как и в #17 сохраняются. Исправь всю логику, а потом уже пойдем тесты проверять

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @categories_available = Category.default_categories.page params[:page]
Пагинация (в нашем случае не хватает количесво объектов на страницу) у нас тоже должна быть настраиваемым параметром. Т.е. тоже должна идти, как параметр. Вот как оно должно быть.
```
.page(params[:page]).per(params[:per_page])
```

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +  end
Что это?

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +      flash[:notice] = 'Category created successfully'
Это точно нужно?

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +  end
У нас разве обновления категорий по обычным правилам работают?

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @category = Services::CreateCategoryService.new(params: category_params, user: current_user).call
Не совсем понимаю, зачем это инстансная переменная

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/models/category.rb
> +  paginates_per 15
Это как пагинация по умолчанию работает?

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/models/category.rb
> +  scope :default_categories, -> { where.not(id: UserCategory.select(:category_id)) }
Не совсем понимаю логику происходящего. Можешь пожалуйста объяснить?

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/services/services.rb
Что с названием файла? Оно же никак не соответствует названию класса

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/services/services.rb
> +    attr_reader :params, :user
Это не обязательно, а если хочешь добавить, то можно в приват закинуть

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/services/services.rb
> +    def initialize(params:, user:)
Давай сделаем более точно имя для `params`

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/services/services.rb
> +    end
Туту у тебя реализован такой сценарий: если категория существует, то мы ничего не делаем, если не существует, то создаем и добавляем её к пользователю. Не думаю, что это правильно. Может быть лучше по имени найти или создать? А к пользователю мы в любом случае должны будем её добавить. Как считаешь?

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on app/views/categories/partials/_user_category.html.erb
> +    <%= button_to t('btn.delete'), category_path(category.id),  method: :delete, class: "btn btn-outline-danger"%>
Вечная у тебя проблема с пробелами...

2023-09-21 06:50 UTC, TsikhanauDzmitry commented on config/routes.rb
> +      get :own, on: :collection
Не совсем понимаю, зачем это вообще добавлять?

2023-09-24 17:29 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +    @categories_available = Category.default_categories.page params[:page]
Исправлено

2023-09-24 17:30 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +  end
Удалено. Было сделано для того, чтобы пользователей смог переходить на страничку своих категорий.

2023-09-24 17:30 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +      flash[:notice] = 'Category created successfully'
Исправил

2023-09-24 17:30 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +  end
Исправил

2023-09-24 17:30 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +    @category = Services::CreateCategoryService.new(params: category_params, user: current_user).call
Исправил

2023-09-24 17:30 UTC, The7Fame commented on app/services/services.rb
> +    attr_reader :params, :user
Закинул в приват

2023-09-24 17:31 UTC, The7Fame commented on app/services/services.rb
> +    def initialize(params:, user:)
Исправил как `category_params`

2023-09-24 17:31 UTC, The7Fame commented on app/services/services.rb
> +    end
Исправил

2023-09-24 17:31 UTC, The7Fame commented on app/views/categories/partials/_user_category.html.erb
> +    <%= button_to t('btn.delete'), category_path(category.id),  method: :delete, class: "btn btn-outline-danger"%>
Исправил

2023-09-24 17:31 UTC, The7Fame commented on config/routes.rb
> +      get :own, on: :collection
Удалил

2023-09-24 17:32 UTC, The7Fame commented on app/models/category.rb
> +  paginates_per 15
Да

2023-09-25 08:20 UTC, TsikhanauDzmitry requested changes

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +      render :new, status: :unprocessable_entity
А почему `render :new`?

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +    end
Странное название для метода

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +                         user_id: user.id).save
Это же обычный метода `create`. Зачем усложнять?

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +    end
Я не нашел ни одного места, где используется этот метод

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
Очень сложный и запутанный сервис. Можно сделать его проще и точнее

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/services/categories_services/update_category_service.rb
Некоторые методы, такие как:
```
    def category_belongs_to_many_users?
      category.users.count > 1
    end

    def create_new_category
      Category.find_or_create_by(category_params)
    end

    def user_include_category?
      user.categories.exists?(category_params)
    end
```
повторяются. Это не есть хорошо. Давай их вынесем в concern, для своих моделей, чтобы отдельно их протестировать, а также просто вызывать самостоятельные методы, которые не будут дублироваться в сервисах

2023-09-25 08:20 UTC, TsikhanauDzmitry commented on app/services/categories_services/update_category_service.rb
Аналогичные замечания, как и в `app/services/categories_services/create_category_service.rb`

2023-09-25 18:26 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +    end
Удалил

2023-09-25 18:27 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +    end
Здесь использовался этот метод

![image](https://github.com/The7Fame/trainee-planner/assets/96648793/88831ffc-974f-4100-88d2-1ad524c770a4)

2023-09-25 18:28 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
Немного переписал его

2023-09-25 18:28 UTC, The7Fame commented on app/services/categories_services/update_category_service.rb
Добавил в консерн

2023-09-25 18:34 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +                         user_id: user.id).save
Согласен. Изменил на `create`

2023-09-25 18:35 UTC, The7Fame commented on app/services/categories_services/update_category_service.rb
Подправил

2023-09-26 07:47 UTC, TsikhanauDzmitry requested changes

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/models/concerns/category_methods.rb
> +  end
На сколько я помню, как раз для такого и были созданы `self` методы

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/models/concerns/category_methods.rb
> +  extend ActiveSupport::Concern
А нельзя просто наследоваться? Или я что-то не правильно понимаю?

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/models/concerns/user_methods.rb
> +  extend ActiveSupport::Concern
А нельзя просто наследоваться? Или я что-то не правильно понимаю?

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/models/concerns/user_methods.rb
> +  def user_include_category?(category_params)
1. Этот метод вызывается у самого пользователя, а значит будет что-то типа: `user.user_include_category?`. Думаю, что название нужно укоротить с помощью удаления `user` в самом начале.
2. Почему передаются параметры категории, а не сама категория?
3. Все параметры в методах должны быть явные, как и в инициализации сервисов

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/models/concerns/category_methods.rb
> +  def category_belongs_to_many_users?
Этот метод вызывается у самой категории, а значит будет что-то типа: `category.category_belongs_to_many_users?`. Думаю, что название нужно укоротить с помощью удаления `category` в самом начале.

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/models/concerns/category_methods.rb
> +    def create_category(category_params)
Все параметры в методах должны быть явные, как и в инициализации сервисов

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +      Category.create_category(category_params).valid? ? add_category_to_user : category.save
`Category.create_category(category_params).valid?`

А как это может быть не валидно? У тебя же `find_or_create_by(category_params)` внутрь заложен. Он в любом случае вернет валидный объект.

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +    end
На мой взгляд метод должен выглядеть очень просто:
```
		Category.create_category(category_params:)
		add_category_to_user
```

У нас при любом раскладе будет создана категория, а потом мы просто добавим её к пользователю.

2023-09-26 07:47 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +        UserCategory.create(category: Category.create_category(category_params),
`Category.create_category(category_params)`, а зачем еще раз создавать категорию? Ты же её уже создал...

2023-09-26 08:26 UTC, TimurShakhlai approved these changes

2023-09-26 18:39 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +        UserCategory.create(category: Category.create_category(category_params),
Точно, теперь один раз.

2023-09-26 18:40 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +    end
Да, но я добавил изначально проверку, пусто ли поле `name`.

2023-09-26 18:44 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +      Category.create_category(category_params).valid? ? add_category_to_user : category.save
Немного не соглашусь, если `name` будет пустым или` name` будет занято, то при вызове `valid?` будет` false`. 
Исправил изначальную проверку, добавил проверку на пустоту `category_params[:name].empty?`

2023-09-26 18:44 UTC, The7Fame commented on app/models/concerns/category_methods.rb
> +    def create_category(category_params)
Исправил

2023-09-26 18:44 UTC, The7Fame commented on app/models/concerns/category_methods.rb
> +  def category_belongs_to_many_users?
Укоротил, исправлено

2023-09-26 18:45 UTC, The7Fame commented on app/models/concerns/user_methods.rb
> +  def user_include_category?(category_params)
Исправлено

2023-09-26 18:46 UTC, The7Fame commented on app/models/concerns/user_methods.rb
> +  extend ActiveSupport::Concern
Модуль не может наследоваться от другого модуля, но он может включать или расширять другой модуль.

2023-09-26 18:46 UTC, The7Fame commented on app/models/concerns/category_methods.rb
> +  extend ActiveSupport::Concern
Модуль не может наследоваться от другого модуля, но он может включать или расширять другой модуль.

2023-09-26 18:59 UTC, The7Fame commented on app/controllers/categories_controller.rb
> +      render :new, status: :unprocessable_entity
Исправил

2023-09-26 19:01 UTC, The7Fame commented on app/models/concerns/category_methods.rb
> +  end
В `extend ActiveSupport::Concern` можно определить методы классы несколькими способами, переписал с `self`.

2023-09-28 06:45 UTC, The7Fame commented on app/models/concerns/category_methods.rb
> +  end
Исправлено

2023-09-28 07:17 UTC, TsikhanauDzmitry requested changes

2023-09-28 07:17 UTC, TsikhanauDzmitry commented on app/services/categories_services/create_category_service.rb
> +      if category_params[:name].empty?
Не уверен, что использовать `empty?` - правильное решение. Если передать `nil`, то у тебя появится сообщение `NoMethodError: undefined method `empty?' for nil:NilClass`, что полностью сломает приложение.

2023-09-28 07:17 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +  end
Давай это вынесем и будем тестировать тот концерн, в котором это добавлено

2023-09-28 07:17 UTC, TsikhanauDzmitry commented on spec/models/category_spec.rb
> +  end
Давай это вынесем и будем тестировать тот концерн, в котором это добавлено

2023-09-28 08:40 UTC, The7Fame commented on app/services/categories_services/create_category_service.rb
> +      if category_params[:name].empty?
Исправил

2023-09-28 08:40 UTC, The7Fame commented on spec/models/user_spec.rb
> +  end
Вынес в `spec/concerns`

2023-09-28 08:40 UTC, The7Fame commented on spec/models/category_spec.rb
> +  end
Вынес в `spec/concerns`

2023-09-28 11:19 UTC, TimurShakhlai submitted a review, later dismissed

2023-10-02 07:52 UTC, TsikhanauDzmitry approved these changes

2023-10-02 08:09 UTC, merged