Event model
The7Fame/trainee-planner pull request #16
Opened 2023-08-17 05:59 UTC by The7Fame

2023-08-24 09:40 UTC, TimurShakhlai approved these changes

2023-08-25 09:01 UTC, TimurShakhlai approved these changes

2023-08-25 09:37 UTC, TsikhanauDzmitry requested changes

2023-08-25 09:37 UTC, TsikhanauDzmitry commented on app/models/category.rb
> +  validates :name, uniqueness: true
Только что смотрел #14 : и там была другая реализация и логика

2023-08-25 09:37 UTC, TsikhanauDzmitry commented on app/models/category.rb
Далее я увидел следующий код:
```
class Event < ApplicationRecord
  belongs_to :category, dependent: :destroy
```
Почему в данном классе я не вижу никаких связей с моделью `Event`?

2023-08-25 09:37 UTC, TsikhanauDzmitry commented on db/migrate/20230817055542_create_events.rb
> +      t.belongs_to :user, null: false, foreign_key: true
Я бы отделил пустой строчкой ассоциации и обычные поля

2023-08-25 09:37 UTC, TsikhanauDzmitry commented on db/migrate/20230817055542_create_events.rb
Является ли данная модель - соеденительной таблицей между пользователями и категориями?

2023-08-25 09:37 UTC, TsikhanauDzmitry commented on spec/factories/events.rb
> +  trait :description do
Не совсем правильное название у трейта

2023-08-25 09:37 UTC, TsikhanauDzmitry commented on spec/models/event_spec.rb
Ассоциации были добавлены не только к модели Event. Где тесты у юзера и категорий?

2023-08-28 06:06 UTC, The7Fame commented on app/models/category.rb
> +  validates :name, uniqueness: true
Исправил, теперь одинаково

2023-08-28 06:06 UTC, The7Fame commented on app/models/category.rb
Добавил

2023-08-28 06:06 UTC, The7Fame commented on db/migrate/20230817055542_create_events.rb
> +      t.belongs_to :user, null: false, foreign_key: true
Отделил

2023-08-28 06:06 UTC, The7Fame commented on spec/models/event_spec.rb
Добавлены

2023-08-28 06:09 UTC, The7Fame commented on db/migrate/20230817055542_create_events.rb
Да, так как модель ссылается на модель пользователей и категорий.

2023-08-28 07:40 UTC, The7Fame commented on spec/factories/events.rb
> +  trait :description do
Исправил

2023-08-28 10:49 UTC, TimurShakhlai approved these changes

2023-08-28 13:42 UTC, TsikhanauDzmitry requested changes

2023-08-28 13:42 UTC, TsikhanauDzmitry commented on db/migrate/20230817055542_create_events.rb
Ты не правильно понял меня. Смотри, есть несколько видов ассоциаций has_many:

1. [has_many](https://edgeguides.rubyonrails.org/association_basics.html#the-has-many-association)
2. [has_many :through](https://edgeguides.rubyonrails.org/association_basics.html#the-has-many-through-association)
3. [has_and_belongs_to_many](https://edgeguides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association)

Какая из этих ассоциаций тебе нужна? Можешь рассказать бизнес-логику, которую ты закладываешь, чтобы я тебя чуть что подправил

2023-08-31 13:16 UTC, TsikhanauDzmitry requested changes

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +  validates :name, :date_time, presence: true
Есть ли какие-нибудь валидации на date_time?

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on app/models/category.rb
> +  has_many :events, dependent: :destroy
has_many :categories, through: :events

Это хранится в моделе пользователя. У категорий разве не должно быть тогда связи с пользователями? Или у пользователя - это лишняя связь?

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on db/migrate/20230817055542_create_events.rb
> +      t.datetime :date_time, null: false
За что отвечает это поле?

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on spec/factories/events.rb
> +    name { 'Meetup' }
Почему не используется Faker?

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
У категорий тоже есть ассоциации. Почему нет тестов?

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on spec/models/event_spec.rb
> +  subject(:event) { build :event }
скобочки

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on spec/models/event_spec.rb
> +  end
Мы же вроде бы делали отдельный describe с трейтами. или я что-то путаю?

2023-08-31 13:16 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +    let(:user) { build(:user) }
А разве у нас в начале не был создан сабджект?

2023-09-01 12:06 UTC, The7Fame commented on app/models/category.rb
> +  has_many :events, dependent: :destroy
Решил добавить `has_many :categories, through: :events`, так как, когда будет поиск, чтобы в дропдауне были те категории, которые использовал пользователь , когда создавал то или иное событие.

2023-09-01 12:06 UTC, The7Fame commented on spec/factories/events.rb
> +    name { 'Meetup' }
Исправил

2023-09-01 12:06 UTC, The7Fame commented on db/migrate/20230817055542_create_events.rb
> +      t.datetime :date_time, null: false
Оно отвечает за дату события. Переименовал

2023-09-01 14:11 UTC, The7Fame commented on app/models/event.rb
> +  validates :name, :date_time, presence: true
Добавил

2023-09-01 14:13 UTC, TimurShakhlai approved these changes

2023-09-01 14:17 UTC, The7Fame commented on spec/models/user_spec.rb
> +    let(:user) { build(:user) }
Исправлено

2023-09-01 14:17 UTC, The7Fame commented on spec/models/user_spec.rb
Добавлен

2023-09-04 09:20 UTC, TimurShakhlai approved these changes

2023-09-04 11:29 UTC, The7Fame commented on spec/models/event_spec.rb
> +  end
Здесь не делали, исправил.

2023-09-06 07:42 UTC, The7Fame commented on spec/models/event_spec.rb
> +  subject(:event) { build :event }
Исправил

2023-09-06 08:21 UTC, TsikhanauDzmitry requested changes

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on app/models/category.rb
> +  has_many :events, dependent: :destroy
@The7Fame если у пользователя есть категории, то категории принадлежат пользователю?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on app/models/user.rb
> +  has_many :categories, through: :events
Меня правда до сих пор эта реализация смущает...

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
А если будет другая модель с другими валидациями дат. Можно ли будет использовать этот модуль?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +  end
А как валидатор догадывается, что `reminder_on` и `event_date` - поля объекта `Event`?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +    user: User.find(rand(1..5))
Что будет если, я сначала создам своего пользователя, а потом запущу сиды? Либо воьму и удалю пользователей и категории, а потом заново запущу сиды?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +  Event.create(
Может лучше с `!` сделать?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on spec/factories/events.rb
> +    event_date { Faker::Date.between(from: DateTime.now.tomorrow, to: 1.year.from_now) }
В сидах и фактори у тебя отличаются реализации. В сидах:
```
event_date: [Faker::Date.between(from: Time.zone.tomorrow, to: 1.year.from_now)].sample
```
А тут инчае. Почему так?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on spec/models/event_spec.rb
> +  describe 'date is not valid' do
Почему не в блоке валидаций?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on spec/models/event_spec.rb
> +    let(:event) { build(:event) }
У тебя же и так ивенты в сабджекте созданы. Зачем еще раз?

2023-09-06 08:21 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +    if reminder_on.past?
Окей. Если у нас был создан завтрашний день, то через 2 дня объект уже не валиден? Или как-то инчае нужно это реализовывать?

2023-09-07 07:07 UTC, The7Fame commented on app/validators/date_validator.rb
> +    if reminder_on.past?
Изменил. Добавил проверку только в тот момент, когда значение даты напоминания изменяется.

2023-09-07 07:08 UTC, The7Fame commented on spec/models/event_spec.rb
> +    let(:event) { build(:event) }
Исправил.

2023-09-07 07:09 UTC, The7Fame commented on spec/models/event_spec.rb
> +  describe 'date is not valid' do
Изначально подумал, что надо сделать отдельно, так как самописные проверки, но лучше, конечно, если это будет в блоке валидаций. Добавил.

2023-09-07 07:10 UTC, The7Fame commented on spec/factories/events.rb
> +    event_date { Faker::Date.between(from: DateTime.now.tomorrow, to: 1.year.from_now) }
Пробовал разные реализации дат, не исправил, остановился на DateTime.

2023-09-07 07:10 UTC, The7Fame commented on db/seeds/development.rb
> +  Event.create(
Да, сделал.

2023-09-07 07:10 UTC, The7Fame commented on db/seeds/development.rb
> +    user: User.find(rand(1..5))
События будут добавлены не тем юзерам. Исправил.

2023-09-07 07:28 UTC, The7Fame commented on app/validators/date_validator.rb
> +  end
В ActiveSupport::Concern описаны методы и поля, то есть что и каким образом валидировать. ActiveSupport::Concern не знает об атрибутах, Concern делегирует проверку методам. И когда подключаем модуль к модели , то ActiveRecord добавляет методы в класс и использует их в качестве проверки.

2023-09-07 07:28 UTC, The7Fame commented on app/validators/date_validator.rb
В целом, можно будет переиспользовать, если в модели в будут такие же поля event_date и reminder_on.

2023-09-07 08:50 UTC, The7Fame commented on app/models/category.rb
> +  has_many :events, dependent: :destroy
Да, можно реализовать через :through.

2023-09-07 08:51 UTC, The7Fame commented on app/models/user.rb
> +  has_many :categories, through: :events
Удалил эту реализацию `has_many :categories, through: :events`.

2023-09-07 10:29 UTC, TimurShakhlai approved these changes

2023-09-07 13:25 UTC, TsikhanauDzmitry requested changes

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
Нет. Нельзя будет переиспользовать(

В этом и главная проблема. В таком случае нужно:
1. Передавать объект, который валидируется
2. Делать, допустим, строгий валидатор только для Event'ов

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +    if reminder_on.past?
Создание объекта сразу с указанием значения даты напоминания - это будет считаться за изменением поля?

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +    return if reminder_on.blank?
Исходя из твоей новой проверки, эта проверка не имеет смысла... Как считаешь?

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +    return if reminder_on.blank?
Или же мы можем сделать `reminder_on = nil`?

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +    elsif reminder_on > event_date
А если `event_date` будет `nil`? И тогда второй вопрос. Есть ли разница, в каком порядке будут указаны валидации?

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +      errors.add(:event_date, "can't be blank")
Чем это отличается от валидации `presence: true`?

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on spec/factories/events.rb
> +    event_date { Faker::Date.between(from: DateTime.now.tomorrow, to: 1.year.from_now) }
Так почему в сидах у тебя `[].sample`, а тут просто метод?

2023-09-07 13:25 UTC, TsikhanauDzmitry commented on spec/models/event_spec.rb
> +      it { expect(event).to validate_presence_of :event_date }
Где в самой модели есть проверка на существование?

2023-09-07 13:57 UTC, The7Fame commented on spec/models/event_spec.rb
> +      it { expect(event).to validate_presence_of :event_date }
В самой модели убрал, в тестах тоже брал. Исправил

2023-09-07 14:00 UTC, The7Fame commented on app/validators/date_validator.rb
> +      errors.add(:event_date, "can't be blank")
Первое - это пользовательская проверка,  а второе - это встроенный помощник.
Выполняют одинаковую логику: проверяют поле на пустоту.

2023-09-07 14:02 UTC, The7Fame commented on app/validators/date_validator.rb
> +    return if reminder_on.blank?
Можем сделать `reminder_on = nil`

2023-09-07 14:04 UTC, The7Fame commented on app/validators/date_validator.rb
> +    if reminder_on.past?
Да, будет считаться за изменение.

2023-09-07 14:23 UTC, The7Fame commented on app/validators/date_validator.rb
> +    elsif reminder_on > event_date
Event_date не может быть `nil`.
Скорее всего, что да, Выполнение идёт сверху вниз , и если одна из валидаций была выше, то её ошибка будет первее.

2023-09-07 14:24 UTC, The7Fame commented on spec/factories/events.rb
> +    event_date { Faker::Date.between(from: DateTime.now.tomorrow, to: 1.year.from_now) }
Моя ошибка, всё к одному виду привёл, а `sample` не убрал. Извини.

2023-09-08 07:45 UTC, TimurShakhlai approved these changes

2023-09-08 11:45 UTC, TsikhanauDzmitry requested changes

2023-09-08 11:45 UTC, TsikhanauDzmitry commented on app/validators/date_validator.rb
> +    raise 'DateValidator module can only use in Event class' unless self == Event
Это правда очень плохое решение для присваивания Ивенту валидатора...

2023-09-11 08:06 UTC, The7Fame commented on app/validators/date_validator.rb
> +    raise 'DateValidator module can only use in Event class' unless self == Event
Вынес проверки в модель

2023-09-11 13:57 UTC, TsikhanauDzmitry requested changes

2023-09-11 13:57 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +  end
Это все должно быть в private блоке

2023-09-11 13:57 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +      errors.add(:event_date, "can't be blank")
Думаю, что достаточно использовать presence. Как считаешь?

2023-09-11 13:57 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +      errors.add(:event_date, "can't be in the past")
Что именно считается прошлым? Как данный метод реагирует на разные часовые пояса?

2023-09-12 05:34 UTC, The7Fame commented on app/models/event.rb
> +      errors.add(:event_date, "can't be blank")
Соглашусь, исправил.

2023-09-12 05:35 UTC, The7Fame commented on app/models/event.rb
> +  end
Сделано.

2023-09-12 05:35 UTC, The7Fame commented on app/models/event.rb
> +      errors.add(:event_date, "can't be in the past")
Никак не реагирует на часовые пояса. Добавил `in_time_zone('UTC')`, чтобы был единый формат при сравнении дат.

2023-09-12 07:42 UTC, TimurShakhlai approved these changes

2023-09-12 08:38 UTC, TsikhanauDzmitry requested changes

2023-09-12 08:38 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +    return unless event_date&.past?
Рекомендую избавляться от `unless` проверок

2023-09-12 08:38 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +      errors.add(:reminder_on, "can't be greater than event date")
А может ли быть `reminder_on == event_date`?

2023-09-12 11:59 UTC, The7Fame commented on app/models/event.rb
> +      errors.add(:reminder_on, "can't be greater than event date")
Да, но уже нет, добавил проверку.

2023-09-12 12:00 UTC, The7Fame commented on app/models/event.rb
> +    return unless event_date&.past?
Заменил на `if`.

2023-09-12 14:07 UTC, TimurShakhlai approved these changes

2023-09-13 07:35 UTC, TsikhanauDzmitry requested changes

2023-09-13 07:35 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +      errors.add(:reminder_on, "can't be greater than event date")
Я думаю, что проверки можно объединить. И вместо:
```
    elsif reminder_on == event_date
      errors.add(:reminder_on, "can't be match event date")
    elsif reminder_on > event_date
      errors.add(:reminder_on, "can't be greater than event date")
```

Сделать что-то типа:

```
    elsif reminder_on >= event_date
      errors.add(:reminder_on, "can't be equal or greater than event date")
```

2023-09-13 10:14 UTC, The7Fame commented on app/models/event.rb
> +      errors.add(:reminder_on, "can't be greater than event date")
Сделано

2023-09-13 10:19 UTC, TsikhanauDzmitry approved these changes

2023-09-13 12:06 UTC, merged