Event controllers views
The7Fame/trainee-planner pull request #17
Opened 2023-08-17 08:23 UTC by The7Fame

2023-09-15 06:21 UTC, TimurShakhlai approved these changes

2023-09-18 07:14 UTC, TsikhanauDzmitry requested changes
Дальше контроллеров и хэлпера не смотрел

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on .rubocop.yml
> +    - app/controllers/*.rb
Зачем это было добавлено?

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +    @events = current_user.events.page(params[:page]).per(20)
Мне не нравится такая реализация пагинации. Это все должно приходить параметрами, а не задаваться в контроллере

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +      redirect_to events_path
1. Это можно и в одну строчку написать
2. Где реализация русского языка?

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +      redirect_to events_path
1. Это можно и в одну строчку написать
2. Где реализация русского языка?

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +      redirect_to events_path
1. Это можно и в одну строчку написать
2. Где реализация русского языка?

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on app/helpers/events_helper.rb
Зачем это было добавлено?

2023-09-18 07:14 UTC, TsikhanauDzmitry commented on app/controllers/search_controller.rb
Давай поиск реализовывать другим ПРом

2023-09-18 11:18 UTC, The7Fame commented on app/helpers/events_helper.rb
Данный файл создаётся автоматически во время генерации контроллера.
В данный файл можно положить методы, которые будут использоваться на уровне views.
Удалил этот файл, так как он не используется.

2023-09-18 11:18 UTC, The7Fame commented on app/controllers/events_controller.rb
> +      redirect_to events_path
Исправлено, добавлено

2023-09-18 11:18 UTC, The7Fame commented on app/controllers/events_controller.rb
> +      redirect_to events_path
Исправлено, добавлено

2023-09-18 11:18 UTC, The7Fame commented on app/controllers/events_controller.rb
> +      redirect_to events_path
Исправлено, добавлено

2023-09-18 11:18 UTC, The7Fame commented on app/controllers/events_controller.rb
> +    @events = current_user.events.page(params[:page]).per(20)
Исправлено

2023-09-18 11:19 UTC, The7Fame commented on .rubocop.yml
> +    - app/controllers/*.rb
Удалено

2023-09-18 11:20 UTC, The7Fame commented on app/controllers/search_controller.rb
Хорошо

2023-09-18 14:07 UTC, TimurShakhlai approved these changes

2023-09-20 06:07 UTC, TimurShakhlai approved these changes

2023-09-21 06:29 UTC, TsikhanauDzmitry requested changes

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +    @events = current_user.events.page params[:page]
Пагинация (в нашем случае не хватает количесво объектов на страницу) у нас тоже должна быть настраиваемым параметром. Т.е. тоже должна идти, как параметр. Вот как оно должно быть.
```
.page(params[:page]).per(params[:per_page])
```

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +    @events = current_user.events.page params[:page]
А порядок, в котором выводятся данные ивенты?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +  paginates_per 20
Это как пагинация по умолчанию работает?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/edit.html.erb
> +      <%= render "events/partials/form", event: @event %>
Почему пропускаешь, `partial:` ?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/index.html.erb
> +    <div id="events"><%= render 'events/partials/events', events: @events %></div>
Почему пропускаешь, `partial:` ?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/new.html.erb
> +    <%=render 'events/partials/form', event: @event %>
Почему пропускаешь, `partial:` ?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/new.html.erb
> +    <%=render 'events/partials/form', event: @event %>
Вечная у тебя проблема с пробелами... Перед `render` забыл поставтить

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/partials/_form.html.erb
> +                            :placeholder => "Category select"}%>
Давай отказываться от старого синтаксиса `=>`

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/partials/_form.html.erb
> +    <%= f.collection_select :category_id, Category.all, :id,:name,
Пользователь может использовать вообще все категории? Или только свои?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/partials/_form.html.erb
> +                            :placeholder => "Category select"}%>
`"Category select"` только на одном языке?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/partials/_form.html.erb
> +    <%= f.submit t('btn.create'), class: "btn btn-primary"%>
Вечная у тебя проблема с пробелами... `class: "btn btn-primary"%>` - после `primary"` пропустил пробел

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/events/show.html.erb
> +      <% if @event.reminder_on%>
Вечная у тебя проблема с пробелами...

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on app/views/kaminari/_first_page.html.erb
Ты как-то менял эти вьюхи? Либо просто добавил?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +100.times do
Прям 100 ивентов?

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on spec/controllers/events/events_controller_destroy_spec.rb
Не правильная структура. Должно быть 2 `describe` блока:
* `when user in not authenticated`
* `when user in authenticated`

Далее в кадом необходимые контексты, но в нашем случае и одного будет достаточно

2023-09-21 06:29 UTC, TsikhanauDzmitry commented on spec/controllers/events/events_controller_destroy_spec.rb
Аналогичные замечания далее

2023-09-22 12:36 UTC, The7Fame commented on app/controllers/events_controller.rb
> +    @events = current_user.events.page params[:page]
Добавил

2023-09-22 12:36 UTC, The7Fame commented on app/controllers/events_controller.rb
> +    @events = current_user.events.page params[:page]
Добавил default_scope, буду выводиться по возрастанию даты.

2023-09-22 12:36 UTC, The7Fame commented on app/models/event.rb
> +  paginates_per 20
Да

2023-09-22 12:37 UTC, The7Fame commented on app/views/events/edit.html.erb
> +      <%= render "events/partials/form", event: @event %>
Исправил

2023-09-22 12:37 UTC, The7Fame commented on app/views/events/index.html.erb
> +    <div id="events"><%= render 'events/partials/events', events: @events %></div>
Исправил

2023-09-22 12:37 UTC, The7Fame commented on app/views/events/partials/_form.html.erb
> +    <%= f.submit t('btn.create'), class: "btn btn-primary"%>
Исправил

2023-09-22 12:37 UTC, The7Fame commented on app/views/events/show.html.erb
> +      <% if @event.reminder_on%>
Исправил

2023-09-22 12:38 UTC, The7Fame commented on app/views/kaminari/_first_page.html.erb
Стилизовал

<img width="155" alt="image" src="https://github.com/The7Fame/trainee-planner/assets/96648793/08110e43-e81b-46c4-914a-fd7624abffd2">

2023-09-22 12:39 UTC, The7Fame commented on db/seeds/development.rb
> +100.times do
Да, добавил 100 ивентов, чтобы сразу можно было пагинацию проверить , дабы не создавать руками.

2023-09-22 12:39 UTC, The7Fame commented on spec/controllers/events/events_controller_destroy_spec.rb
Подправил

2023-09-25 08:24 UTC, TsikhanauDzmitry requested changes

2023-09-25 08:24 UTC, TsikhanauDzmitry commented on app/views/events/new.html.erb
> +    <%=render partial: 'events/partials/form', locals: { event: @event } %>
Опять пробелы...

2023-09-25 08:24 UTC, TsikhanauDzmitry commented on app/views/events/partials/_events.html.erb
> +<%else%>
Опять пробелы...

2023-09-25 08:24 UTC, TsikhanauDzmitry commented on app/views/events/partials/_events.html.erb
> +          locals: { event: event, index: index } %>
В одну строку не помещается?

2023-09-25 08:24 UTC, TsikhanauDzmitry commented on app/views/events/partials/_form.html.erb
> +                            :placeholder => "Category select"} %>
Я уже точно делал замечания про` =>`

2023-09-25 08:24 UTC, TsikhanauDzmitry commented on app/views/events/show.html.erb
> +           method: :delete, class: "btn btn-danger" %>
Опять пробелы

2023-09-25 18:35 UTC, The7Fame commented on app/views/events/new.html.erb
> +    <%=render partial: 'events/partials/form', locals: { event: @event } %>
Исправлено

2023-09-25 18:35 UTC, The7Fame commented on app/views/events/partials/_events.html.erb
> +<%else%>
Исправлено

2023-09-25 18:36 UTC, The7Fame commented on app/views/events/partials/_events.html.erb
> +          locals: { event: event, index: index } %>
Помещается, мне показалось, что так будет красивее. Переписал в одну строчку

2023-09-25 18:36 UTC, The7Fame commented on app/views/events/partials/_form.html.erb
> +                            :placeholder => "Category select"} %>
Исправил

2023-09-25 18:36 UTC, The7Fame commented on app/views/events/show.html.erb
> +           method: :delete, class: "btn btn-danger" %>
Исправил

2023-09-26 08:05 UTC, TsikhanauDzmitry requested changes

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/controllers/events/events_controller_index_spec.rb
А почему нет массива ивентов, который мы должны проверять, как принадлежность?

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/controllers/events/events_controller_show_spec.rb
> +    let(:user) { create(:user) }
У тебя же уже вынесен юзер за дескрайб блок. Зачем он тут?

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/features/events/event_index_spec.rb
А почему нет массива ивентов, который мы должны проверять, как принадлежность?

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/features/events/event_index_spec.rb
> +      end
Это можно в 1 строчку

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/routings/events_routing_spec.rb
> +  it 'routes eEents#create' do
Что с названием?

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/routings/events_routing_spec.rb
> +    expect(get('/events/new')).to route_to(controller: 'events', action: 'new', locale: I18n.default_locale)
Почему не `post` метод?

2023-09-26 08:05 UTC, TsikhanauDzmitry commented on spec/routings/events_routing_spec.rb
> +    expect(get("/events/#{event.id}/edit")).to route_to(controller: 'events', locale: I18n.default_locale,
Почему не `put/patch` метод?

2023-09-26 08:26 UTC, TimurShakhlai approved these changes

2023-09-26 16:25 UTC, The7Fame commented on spec/features/events/event_index_spec.rb
Добавил

2023-09-26 16:25 UTC, The7Fame commented on spec/features/events/event_index_spec.rb
> +      end
Исправил

2023-09-26 16:25 UTC, The7Fame commented on spec/routings/events_routing_spec.rb
> +  it 'routes eEents#create' do
Исправил

2023-09-26 16:25 UTC, The7Fame commented on spec/routings/events_routing_spec.rb
> +    expect(get('/events/new')).to route_to(controller: 'events', action: 'new', locale: I18n.default_locale)
Моя ошибка, исправил

2023-09-26 16:25 UTC, The7Fame commented on spec/routings/events_routing_spec.rb
> +    expect(get("/events/#{event.id}/edit")).to route_to(controller: 'events', locale: I18n.default_locale,
Моя ошибка, исправил

2023-09-26 16:25 UTC, The7Fame commented on spec/controllers/events/events_controller_show_spec.rb
> +    let(:user) { create(:user) }
Согласен, убрал

2023-09-26 16:25 UTC, The7Fame commented on spec/controllers/events/events_controller_index_spec.rb
Добавил

2023-09-28 06:00 UTC, TsikhanauDzmitry requested changes

2023-09-28 06:00 UTC, TsikhanauDzmitry commented on spec/controllers/events/events_controller_show_spec.rb
> +    describe 'when user is not authenticated create event' do
Название не соответствует действительности

2023-09-28 06:00 UTC, TsikhanauDzmitry commented on spec/controllers/events/events_controller_show_spec.rb
> +        show_event
Почему не в `before` блоке?

2023-09-28 06:33 UTC, The7Fame commented on spec/controllers/events/events_controller_show_spec.rb
> +    describe 'when user is not authenticated create event' do
Исправлено

2023-09-28 06:33 UTC, The7Fame commented on spec/controllers/events/events_controller_show_spec.rb
> +        show_event
Добавил

2023-09-28 07:18 UTC, TsikhanauDzmitry requested changes

2023-09-28 07:18 UTC, TsikhanauDzmitry commented on spec/features/events/event_index_spec.rb
> +      end
@The7Fame не исправил

2023-09-28 07:18 UTC, TsikhanauDzmitry commented on spec/routings/events_routing_spec.rb
> +  it 'routes eEents#create' do
@The7Fame не исправил

2023-09-28 07:18 UTC, TsikhanauDzmitry commented on spec/routings/events_routing_spec.rb
> +    expect(get('/events/new')).to route_to(controller: 'events', action: 'new', locale: I18n.default_locale)
@The7Fame не исправил

2023-09-28 07:18 UTC, TsikhanauDzmitry commented on spec/routings/events_routing_spec.rb
> +    expect(get("/events/#{event.id}/edit")).to route_to(controller: 'events', locale: I18n.default_locale,
@The7Fame не исправил

2023-09-28 08:11 UTC, TimurShakhlai submitted a review, later dismissed

2023-09-28 08:38 UTC, The7Fame commented on spec/routings/events_routing_spec.rb
> +    expect(get("/events/#{event.id}/edit")).to route_to(controller: 'events', locale: I18n.default_locale,
Исправил

2023-09-28 08:38 UTC, The7Fame commented on spec/routings/events_routing_spec.rb
> +    expect(get('/events/new')).to route_to(controller: 'events', action: 'new', locale: I18n.default_locale)
Исправил

2023-09-28 08:38 UTC, The7Fame commented on spec/routings/events_routing_spec.rb
> +  it 'routes eEents#create' do
Исправил

2023-09-28 08:38 UTC, The7Fame commented on spec/features/events/event_index_spec.rb
> +      end
Исправил

2023-10-02 07:54 UTC, TsikhanauDzmitry submitted a review, later dismissed

2023-10-02 09:30 UTC, merged