Home controller views
The7Fame/trainee-planner pull request #18
Opened 2023-08-22 13:48 UTC by The7Fame

2023-08-23 06:44 UTC, TimurShakhlai submitted a review, later dismissed

2023-08-24 09:54 UTC, TsikhanauDzmitry requested changes

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/helpers/home_helper.rb
Зачем этот файл?

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +    <h2 class="text-center"><%= t :start %></h2>
Я бы не рекомендовал вызывать это так `<%= t :start %>`. Потом могут возникнуть проблемы, когда очень много текста будет, а также многослойность

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +    <h2 class="text-center"><%= t :start %></h2>
+ отступ слишком большой. Не находишь?

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
> +<!-- Navbar -->
Зачем этот комментарий?

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
> +
Зачем тут пустая строчка?

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
> +    <div class="collapse navbar-collapse" id="navbarButtonsExample">
id использовать обязательно?

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
> +          <a class="navbar-brand"><%=t ('nav.company') %></a>
Везде перед `t` пропустил пробел)

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
> +      </ul>
Зачем добавлять ссылки на то, чего еще нет?

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
Не совсем понимаю название файла...

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_exists-user.html.erb
> +      </ul>
Было бы лучше вынести это в отдельный `partial`

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +<%= render 'layouts/new-user' %>
Я вообще не понял, почему хэдер пустой...

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/_new-user.html.erb
Аналогичные замечания с `app/views/layouts/_exists-user.html.erb` файла

2023-08-24 09:54 UTC, TsikhanauDzmitry commented on app/views/layouts/application.html.erb
>    </body>
Я бы разъеденил бы их пустыми строчками

2023-08-24 09:56 UTC, TsikhanauDzmitry commented
Сделай пожалуйста смену языков в виде дропдауна, а не кнопок

2023-08-24 09:56 UTC, TsikhanauDzmitry commented
Ни одного теста не было написано(

2023-08-25 06:28 UTC, The7Fame commented on app/views/layouts/_exists-user.html.erb
Изменил

2023-08-25 06:29 UTC, The7Fame commented on app/views/layouts/_exists-user.html.erb
> +      </ul>
Добавил в partial

2023-08-25 06:30 UTC, The7Fame commented on app/views/layouts/application.html.erb
>    </body>
Разъединил

2023-08-25 06:30 UTC, The7Fame commented
> Сделай пожалуйста смену языков в виде дропдауна, а не кнопок

Сделано

2023-08-25 06:30 UTC, The7Fame commented
> Ни одного теста не было написано(

Написал

2023-08-25 06:30 UTC, The7Fame commented on app/views/layouts/_exists-user.html.erb
> +
Исправил

2023-08-25 06:31 UTC, The7Fame commented on app/views/layouts/_exists-user.html.erb
> +<!-- Navbar -->
В самом начале оставил в файле данный комментарий, чтобы было понятно, что туда писать.
Комментарий удалил

2023-08-25 06:31 UTC, The7Fame commented on app/views/home/index.html.erb
> +    <h2 class="text-center"><%= t :start %></h2>
Да, нахожу. Поправил

2023-08-25 06:34 UTC, The7Fame commented on app/helpers/home_helper.rb
Данный файл создаётся автоматически во время генерации контроллера.
В данный файл можно положить методы, который будут использоваться на уровне views.
Удалил этот файл, так как он не используется.

2023-08-25 06:34 UTC, The7Fame commented on app/views/layouts/_new-user.html.erb
Исправил

2023-08-25 06:34 UTC, The7Fame commented on app/views/layouts/application.html.erb
>    </body>
Сделано

2023-08-28 10:51 UTC, TimurShakhlai approved these changes, later dismissed

2023-08-30 08:40 UTC, TsikhanauDzmitry requested changes

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/helpers/application_helper.rb
> +  end
Разве внутри devise не содержится этот хелпер?

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +    </h2>
Это можно в одну строчку написать

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +    </h2>
Это можно в одну строчку написать

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +          <a class="navbar-brand"><%=t ('nav.company') %></a>
1. Забываешь пробел после `<%=`
2. Тэг `a` - это же ссылка. Зачем она тут? И если нужна ссылка, то логичнее было бы использовать `rails-helper` такой как `link_to`
3. Если это все-таки ссылка, то куда она ведет?

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +        <%= render 'layouts/user-login' %>
Правильнее было бы использовать [partial](https://guides.rubyonrails.org/layouts_and_rendering.html#partial-layouts), как в статье

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +</nav>
Как-то тут все отсупы съехали. Не находишь?

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +        <%= render 'layouts/user-login' %>
Далее такие же моменты, просто не буду каждый выделять.

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_locales.html.erb
> +    <li><%= link_to t('nav.ru'), {locale: :ru}, { class: "dropdown-item" } %></li>
Очень любишь пропускать пробелы...

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
> +      </div>
Табулирование вышло из чата(

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
> +        <button class="btn btn-danger"><%= t('user.sign_out') %> </button>
Используй `button_to` хэлпер, а не html-кнопки

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +          <a class="navbar-brand"><%=t ('nav.company') %></a>
Далее ты тоже ссылки передаешь через `a`. Везде должен быть `link_to`

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-login.html.erb
> +  <a class="nav-link" href="#"><%=t ('nav.categories') %></a>
Все модели, контроллеры и вьюхи еще не были добавлены. А значит и ссылок на них не должно быть

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/_user-signin.html.erb
> +  <button class="btn btn-primary"><%= t('user.sign_up')%></button>
Используй `button_to` хэлпер, а не html-кнопки

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on app/views/layouts/mailer.html.erb
> -
Зачем?

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on config/database.yml
> +  password: <%= ENV.fetch("POSTGRES_PASSWORD") { '1234' } %>
Как эти изменения относятся к PR?

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> +    end
Не совсем понимаю данный тест. Какой статус возвращает метод контроллера?

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on spec/features/home_spec.rb
Замечательно, что сделал фича тесты, но забыл отдельные тесты на view

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on spec/features/home_spec.rb
> +  end
Думаю, что рационально было бы сделать отдельные фича тесты для смены языков

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on spec/features/home_spec.rb
Общее замечание: все действия должны быть в `before` блоках. Никаких действий в `it`

2023-08-30 08:40 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
Где тесты на роутинг?

2023-09-01 07:02 UTC, The7Fame commented on spec/controllers/home_controller_spec.rb
Добавил

2023-09-01 07:02 UTC, The7Fame commented on spec/features/home_spec.rb
Исправил

2023-09-01 07:02 UTC, The7Fame commented on spec/features/home_spec.rb
> +  end
Переписал

2023-09-01 07:02 UTC, The7Fame commented on spec/features/home_spec.rb
Добавил тесты на view

2023-09-01 07:02 UTC, The7Fame commented on spec/controllers/home_controller_spec.rb
> +    end
Исправил, должен возвращать 200

2023-09-01 07:02 UTC, The7Fame commented on app/views/layouts/_header.html.erb
> +        <%= render 'layouts/user-login' %>
Изменил

2023-09-01 07:02 UTC, The7Fame commented on app/views/layouts/_header.html.erb
> +          <a class="navbar-brand"><%=t ('nav.company') %></a>
Здесь никуда не должна вести ссылки, изменил тэг` а`.
Заменил `a` на` link_to`, `button` на ` button_to`

2023-09-01 07:02 UTC, The7Fame commented on app/views/home/index.html.erb
> +    </h2>
Сделано

2023-09-01 07:02 UTC, The7Fame commented on app/views/home/index.html.erb
> +    </h2>
Сделано

2023-09-01 07:02 UTC, The7Fame commented on app/helpers/application_helper.rb
> +  end
Есть такой helper, но так как это хедер и пока devise не используется, решил сделать helper.

2023-09-01 10:47 UTC, TimurShakhlai submitted a review, later dismissed

2023-09-04 09:21 UTC, TimurShakhlai approved these changes, later dismissed

2023-09-05 06:53 UTC, TsikhanauDzmitry requested changes

2023-09-05 06:53 UTC, TsikhanauDzmitry commented on app/views/layouts/mailer.html.erb
> -
@The7Fame  Ответа не последовало(

2023-09-05 06:53 UTC, TsikhanauDzmitry commented on spec/features/home_spec.rb
> +    end
Если в `before` блоке 1 строка, то можно писать через `{ }`

2023-09-05 06:53 UTC, TsikhanauDzmitry commented on spec/features/home_spec.rb
> +    end
Далее аналогичная проблема

2023-09-05 07:17 UTC, The7Fame commented on app/views/layouts/mailer.html.erb
> -
Странно , что не отправилось сообщение.
Случайно строчку удалил, вернул всё на место.

2023-09-05 07:23 UTC, The7Fame commented on spec/features/home_spec.rb
> +    end
Исправил, где 1 строка в `before` блоках

2023-09-05 09:32 UTC, TimurShakhlai approved these changes

2023-09-05 10:05 UTC, TsikhanauDzmitry approved these changes

2023-09-05 11:12 UTC, merged