Fix home page
The7Fame/trainee-planner pull request #28
Opened 2023-09-15 11:27 UTC by The7Fame

2023-09-15 12:00 UTC, TimurShakhlai submitted a review, later dismissed

2023-09-18 07:05 UTC, TsikhanauDzmitry requested changes

2023-09-18 07:05 UTC, TsikhanauDzmitry commented on app/controllers/home_controller.rb
> +  before_action :authenticate_user!
Не соглашусь с такой реализацией. Думаю, что правильнее было бы сделать вариацию с тем, что юзер залогинен, либо нет. Если нет, то показывать какую-нибудь картинку, если да, то то, что ты уже реализуешь

2023-09-18 07:05 UTC, TsikhanauDzmitry commented on app/controllers/home_controller.rb
> +                                                    DateTime.now.beginning_of_day, DateTime.now.end_of_day).count
Каждый раз обращаться к пользователю, а потом к его ивентам - это не есть правильно. Также очень пугают SQL запросы прямо в контроллере

2023-09-18 07:05 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> +      end
У тебя помимо этого есть еще какие-то объекты, которые вызываются на индексе. Разве нет?

2023-09-18 07:05 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +      <p><%= t ('user.today_events') %> <%= @count_events_today %></p>
Что будет, если ивентов вообще нет?

2023-09-18 07:05 UTC, TsikhanauDzmitry commented on spec/features/home/home_index_spec.rb
> +    end
А где тесты на количество ивентов?

2023-09-18 07:05 UTC, TsikhanauDzmitry commented on spec/views/home/index.html.erb_spec.rb
>    end
А где тесты на количество ивентов?

2023-09-18 15:48 UTC, The7Fame commented on app/controllers/home_controller.rb
> +                                                    DateTime.now.beginning_of_day, DateTime.now.end_of_day).count
Убрал

2023-09-18 15:50 UTC, TimurShakhlai submitted a review, later dismissed

2023-09-18 16:01 UTC, The7Fame commented on spec/controllers/home_controller_spec.rb
> +      end
Partials отличаются, если юзер вошёл в систему или ещё нет.

2023-09-18 16:02 UTC, The7Fame commented on app/views/home/index.html.erb
> +      <p><%= t ('user.today_events') %> <%= @count_events_today %></p>
Если нет ивентов, то количество будет равно 0.

2023-09-18 16:02 UTC, The7Fame commented on spec/features/home/home_index_spec.rb
> +    end
Добавил.

2023-09-18 16:02 UTC, The7Fame commented on spec/views/home/index.html.erb_spec.rb
>    end
Добавил.

2023-09-18 16:31 UTC, TimurShakhlai approved these changes, later dismissed

2023-09-19 05:59 UTC, TsikhanauDzmitry requested changes

2023-09-19 05:59 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +        <p><%= t ('user.today_events') %> <%= current_user.events.today.count %></p>
Очень не приветствую логику во вьюхах. Давай сделаем `Presenter`

2023-09-19 05:59 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
> +  render_views
Зачем это?

2023-09-19 05:59 UTC, TsikhanauDzmitry commented on spec/views/home/index.html.erb_spec.rb
> +    expect(rendered).to have_content('You have events in future: 1')
Тут вроде для точности можно использовать `I18`, чтобы языки точные не писать

2023-09-19 07:49 UTC, The7Fame commented on app/controllers/home_controller.rb
> +  before_action :authenticate_user!
Исправлено

2023-09-19 07:49 UTC, The7Fame commented on app/views/home/index.html.erb
> +        <p><%= t ('user.today_events') %> <%= current_user.events.today.count %></p>
Сделано

2023-09-19 07:51 UTC, The7Fame commented on spec/views/home/index.html.erb_spec.rb
> +    expect(rendered).to have_content('You have events in future: 1')
Исправлено

2023-09-19 07:58 UTC, The7Fame commented on spec/controllers/home_controller_spec.rb
> +  render_views
Чтобы проверить подгружаются ли partials, по умолчанию этого нет

2023-09-19 11:51 UTC, TimurShakhlai approved these changes, later dismissed

2023-09-19 13:14 UTC, TsikhanauDzmitry requested changes

2023-09-19 13:14 UTC, TsikhanauDzmitry commented on app/presenters/user_presenter.rb
> +  end
Думаю, что тут можно имя с  фамилией выводить. Если фамилии нет, то только имя

2023-09-19 13:14 UTC, TsikhanauDzmitry commented on app/views/home/index.html.erb
> +      <% presenter = UserPresenter.new(current_user) %>
1. Никакой логики во вьюхах.
2. Давай лучше расширим метод контроллера. Думаю, что так будет лучше всего:
```
def index
  @user = UserPresenter.new(current_user) if current_user
end
```
3. Давай вынесем часть пользователя и часть без пользователя в отдельный паршалы?

2023-09-19 13:14 UTC, TsikhanauDzmitry commented on spec/controllers/home_controller_spec.rb
Как обновишь контроллер, то долдны добавиться и тесты с объектами

2023-09-19 13:14 UTC, TsikhanauDzmitry commented on spec/presenters/user_presenter_spec.rb
> +  end
Неявные тесты. Я должен поверить, что там вообще что-то есть? Создай объекты, которые проверяешь

2023-09-19 14:39 UTC, The7Fame commented on app/views/home/index.html.erb
> +      <% presenter = UserPresenter.new(current_user) %>
Вынес в паршалы части. Поправил index.

2023-09-19 14:39 UTC, The7Fame commented on spec/presenters/user_presenter_spec.rb
> +  end
Сделано

2023-09-19 14:39 UTC, The7Fame commented on spec/controllers/home_controller_spec.rb
Сделано

2023-09-19 15:07 UTC, The7Fame commented on app/presenters/user_presenter.rb
> +  end
Сделано

2023-09-19 15:39 UTC, TimurShakhlai approved these changes, later dismissed

2023-09-20 06:47 UTC, TsikhanauDzmitry requested changes

2023-09-20 06:47 UTC, TsikhanauDzmitry commented on spec/presenters/user_presenter_spec.rb
Не правильные тесты. Ты должен просто протестировать каждый метод отдельно, а не пытаться это делать скоупом

2023-09-20 06:47 UTC, TsikhanauDzmitry commented on spec/views/home/index.html.erb_spec.rb
> +  let(:presenter) { UserPresenter.new(user) }
Давай сменим имя на `:user_presenter`. Думаю, что так будет понятнее

2023-09-20 06:47 UTC, TsikhanauDzmitry commented on spec/views/home/index.html.erb_spec.rb
Где тесты на неавторизированного пользователя?

2023-09-20 06:47 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +                }
Мне не нравится использование sql запросов. Давай лучше сделаем что-то типа: https://piechowski.io/post/how-to-use-greater-than-less-than-active-record/

2023-09-20 07:45 UTC, The7Fame commented on spec/presenters/user_presenter_spec.rb
Исправил

2023-09-20 08:16 UTC, The7Fame commented on spec/views/home/index.html.erb_spec.rb
Добавил

2023-09-20 08:16 UTC, The7Fame commented on app/models/event.rb
> +                }
Исправил

2023-09-20 08:16 UTC, The7Fame commented on spec/views/home/index.html.erb_spec.rb
> +  let(:presenter) { UserPresenter.new(user) }
Изменил

2023-09-20 08:16 UTC, The7Fame commented on spec/presenters/user_presenter_spec.rb
Исправил

2023-09-20 08:36 UTC, TsikhanauDzmitry requested changes

2023-09-20 08:36 UTC, TsikhanauDzmitry commented on spec/presenters/user_presenter_spec.rb
Тут очень много повторения одного и того же кода. Давай вынесем в `subject` сам презентер, а также все остальные повторяющиеся строчки кода, которые могу не повторяться. Сами модельки пользователя спокойно можно через `let` менять

2023-09-20 09:07 UTC, The7Fame commented on spec/presenters/user_presenter_spec.rb
Исправил

2023-09-20 09:22 UTC, TsikhanauDzmitry approved these changes

2023-09-21 05:59 UTC, TimurShakhlai approved these changes

2023-09-21 07:05 UTC, merged