Join table
The7Fame/trainee-planner pull request #29
Opened 2023-09-15 11:28 UTC by The7Fame

2023-09-15 12:00 UTC, TimurShakhlai approved these changes, later dismissed

2023-09-18 06:54 UTC, TsikhanauDzmitry requested changes
Не вижу основных вещей:

1. Тесты
2. Сиды

2023-09-18 06:54 UTC, TsikhanauDzmitry commented on db/migrate/20230915095532_create_users_categories.rb
А почему не сделал модель для этой таблицы?

2023-09-18 06:54 UTC, TsikhanauDzmitry commented on app/models/user.rb
> +  has_and_belongs_to_many :categories
На удаление ничего ставить не будешь?

2023-09-18 17:06 UTC, The7Fame commented on db/migrate/20230915095532_create_users_categories.rb
Исправил

2023-09-18 17:06 UTC, The7Fame commented on app/models/user.rb
> +  has_and_belongs_to_many :categories
Исправил

2023-09-19 05:23 UTC, TsikhanauDzmitry approved these changes

2023-09-19 06:43 UTC, TimurShakhlai approved these changes

2023-09-19 06:46 UTC, merged