Add SearchController
The7Fame/trainee-planner pull request #30
Opened 2023-09-19 03:40 UTC by The7Fame

## Task:
Add SearchController

## Change proposed in this pull request:

1. Add SearchController
2. Add route
3. Add views for SearchController
4. Add translation
5. Add tests for controller
6. Add tests for views

2023-10-03 10:38 UTC, TimurShakhlai approved these changes

2023-10-03 13:58 UTC, TimurShakhlai approved these changes

2023-10-04 08:15 UTC, TsikhanauDzmitry requested changes

2023-10-04 08:15 UTC, TsikhanauDzmitry commented on app/controllers/search_controller.rb
Мне в приницпе не нравится `SearchController`. Если нам придется искать не только ивенты? Давай лучше делать через `SearchQuery`, в которую мы будем передавать параметры и данные, а он уже по ним все найдет и отфильтрует

2023-10-04 08:15 UTC, TsikhanauDzmitry commented on app/views/search/_form.html.erb
> +                                placeholder: "Category select" }
Никакой старой логики (`=>`)

2023-10-04 11:14 UTC, The7Fame commented on app/views/search/_form.html.erb
> +                                placeholder: "Category select" }
Исправлено

2023-10-04 11:14 UTC, The7Fame commented on app/controllers/search_controller.rb
Исправил

2023-10-04 11:32 UTC, TimurShakhlai approved these changes

2023-10-04 14:37 UTC, TimurShakhlai approved these changes

2023-10-05 07:22 UTC, TsikhanauDzmitry approved these changes

2023-10-05 08:23 UTC, merged