Weather api
The7Fame/trainee-planner pull request #32
Opened 2023-09-26 19:54 UTC by The7Fame

2023-10-03 10:37 UTC, TimurShakhlai approved these changes

2023-10-04 08:24 UTC, TsikhanauDzmitry requested changes

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on app/presenters/weather_presenter.rb
> +    (@prediction.presence || 'Information is not available')
`'Information is not available'` должна быть на нескольких языках

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +  LNG = '27.541989'
Это все должно храниться в `ENV` переменных

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on app/presenters/weather_presenter.rb
Миша в общей беседе задал вопрос: "нам нужно доставать погоду по часам или будет достаточно погоды на день?" Мы решили, что лучше сделать почасовую погоду

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +    def initialize(date)
Используем строгие параметры

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on app/presenters/weather_presenter.rb
> +  def initialize(event)
Используем строгие параметры

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +      JSON.parse response.body
параметры всегда передаем в скобках

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on app/views/events/show.html.erb
> +      <p><%= @weather.weather %></p>
Я бы рекомендовал сделать вывод погоды более красивым, чем он у тебя сейчас

2023-10-04 08:24 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +    end
Может лучше было бы, если бы метод возвращал какой-то хэш с только необходимыми данными, а презентер бы тогда делал необходимую строку?

2023-10-04 18:51 UTC, The7Fame commented on app/presenters/weather_presenter.rb
> +    (@prediction.presence || 'Information is not available')
Исправлено

2023-10-04 18:51 UTC, The7Fame commented on lib/weather/forecast.rb
> +  LNG = '27.541989'
Добавил

2023-10-04 18:51 UTC, The7Fame commented on app/presenters/weather_presenter.rb
Сделал отдельное поле, где можно указать любое время.

2023-10-04 18:52 UTC, The7Fame commented on lib/weather/forecast.rb
> +    def initialize(date)
Исправил

2023-10-04 18:52 UTC, The7Fame commented on app/presenters/weather_presenter.rb
> +  def initialize(event)
Исправил

2023-10-04 18:52 UTC, The7Fame commented on lib/weather/forecast.rb
> +      JSON.parse response.body
Исправил

2023-10-04 18:52 UTC, The7Fame commented on app/views/events/show.html.erb
> +      <p><%= @weather.weather %></p>
Изменил на такой вывод

![image](https://github.com/The7Fame/trainee-planner/assets/96648793/9aa06660-6731-4ee3-abca-a50a438e744d)

2023-10-04 18:53 UTC, The7Fame commented on lib/weather/forecast.rb
> +    end
Да, так будет лучше, исправил

2023-10-05 08:00 UTC, TsikhanauDzmitry requested changes

2023-10-05 08:00 UTC, TsikhanauDzmitry commented on app/views/events/partials/_time.html.erb
> +<% end %>
Пустая строчка в конце файла отсутствует

2023-10-05 08:00 UTC, TsikhanauDzmitry commented on app/views/events/partials/_weather.html.erb
> +</div>
Пустая строчка в конце файла отсутствует

2023-10-05 08:00 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +      @datetime = "#{@date} #{@time}"
Не думаю, что правильно хранить это как переменную. Лучше уже метод просто

2023-10-05 13:46 UTC, The7Fame commented on lib/weather/forecast.rb
> +      @datetime = "#{@date} #{@time}"
Исправил

2023-10-05 13:46 UTC, The7Fame commented on app/views/events/partials/_weather.html.erb
> +</div>
Добавил

2023-10-05 13:46 UTC, The7Fame commented on app/views/events/partials/_time.html.erb
> +<% end %>
Добавил

2023-10-05 13:47 UTC, TimurShakhlai approved these changes

2023-10-06 07:41 UTC, TsikhanauDzmitry requested changes

2023-10-06 07:41 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +      @time = @time_params.present? ? "#{@time_params[:time]}:00" : '00:00:00'
Зачем делать инстансную переменную? Она же только в этом методе и используется

2023-10-06 09:54 UTC, The7Fame commented on lib/weather/forecast.rb
> +      @time = @time_params.present? ? "#{@time_params[:time]}:00" : '00:00:00'
Исправил

2023-10-06 10:15 UTC, DariaAres approved these changes, later dismissed

2023-10-09 07:39 UTC, TsikhanauDzmitry requested changes

2023-10-09 07:39 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +    end
Я бы данный метод написал так:

```
    def what_weather
      return unless weather['message'] == 'success'

      info = weather['data']['history'][0]
      sign = info['temperature'].to_i.positive? ? '+' : '-'
      
      {
        on_the_street: info['icon'].capitalize,
        temperature: "#{sign} #{info['temperature']} C",
        summary: (info['summary']).to_s
      }
    end
```

2023-10-09 07:39 UTC, TsikhanauDzmitry commented on lib/weather/forecast.rb
> +    end
По факту просто бы более открыто показал то, что мы возвращаем

2023-10-10 15:54 UTC, The7Fame commented on lib/weather/forecast.rb
> +    end
Исправил

2023-10-10 16:19 UTC, DariaAres approved these changes

2023-10-11 11:51 UTC, TsikhanauDzmitry approved these changes

2023-10-11 13:22 UTC, merged