Notifications by email about coming event
The7Fame/trainee-planner pull request #34
Opened 2023-10-03 12:32 UTC by The7Fame

## Task:
Notifications by email about coming event

## Change proposed in this pull request:

1.  Job
2.  Add Mailer
3.  Add Schedule
4.  Add translation to view

2023-10-06 15:11 UTC, dasha-sync commented on Gemfile
> +
Эти изменения, как и изменения в Gemfile.lock и роутах, относятся к другим пиарам, наверно их все же стоит убрать

2023-10-06 15:11 UTC, DariaAres commented on app/jobs/send_reminder_email_job.rb
> +  end
Что делает этот блок? Может его лучше занести в одтельный метод?

2023-10-09 06:50 UTC, The7Fame commented on Gemfile
> +
Убрал

2023-10-09 06:50 UTC, The7Fame commented on app/jobs/send_reminder_email_job.rb
> +  end
Делает поле reminder_on пустым после того, как джоба выполнится.
Немного изменил, чтобы было понятнее.

2023-10-09 14:12 UTC, DariaAres submitted a review, later dismissed

2023-10-10 07:35 UTC, TsikhanauDzmitry requested changes

2023-10-10 07:35 UTC, TsikhanauDzmitry commented on app/jobs/send_reminder_email_job.rb
> +  end
Согласен с @DariaAres . Сделай отдельный метод, который будет вызываться в `after_perform`

2023-10-10 07:35 UTC, TsikhanauDzmitry commented on app/mailers/reminder_mailer.rb
> +  def reminder(user, event)
Параметры строгие должны быть

2023-10-10 07:35 UTC, TsikhanauDzmitry commented on app/views/reminder_mailer/reminder.html.erb
Почему не на разных языках?

2023-10-10 15:43 UTC, The7Fame commented on app/mailers/reminder_mailer.rb
> +  def reminder(user, event)
Исправлено

2023-10-10 15:43 UTC, The7Fame commented on app/jobs/send_reminder_email_job.rb
> +  end
Исправлено

2023-10-10 15:43 UTC, The7Fame commented on app/views/reminder_mailer/reminder.html.erb
Добавлено

2023-10-10 16:22 UTC, DariaAres submitted a review, later dismissed

2023-10-11 11:54 UTC, TsikhanauDzmitry requested changes
А где тесты? Можно же написать тесты, чтобы проверяли сам текст письма

2023-10-11 11:54 UTC, TsikhanauDzmitry commented on app/jobs/send_reminder_email_job.rb
> +  end
Может быть как-то через метод обновления атрибутов это сделать? Либо обычным update? А то выглядит не серьезно

2023-10-12 12:56 UTC, The7Fame commented on app/jobs/send_reminder_email_job.rb
> +  end
Сделал через update

2023-10-12 13:20 UTC, TsikhanauDzmitry requested changes

2023-10-12 13:20 UTC, TsikhanauDzmitry commented on spec/mailers/reminder_mailer_spec.rb
> +    }
Используем `{ }` только при одной строчке. В этом случае надо через `do-end`, а также добавить название тесту

2023-10-12 15:40 UTC, The7Fame commented on spec/mailers/reminder_mailer_spec.rb
> +    }
Понял, исправил

2023-10-16 07:41 UTC, TsikhanauDzmitry approved these changes

2023-10-17 16:19 UTC, merged