Add gems for testing applications and configure them
The7Fame/trainee-planner pull request #6
Opened 2023-08-03 12:13 UTC by The7Fame

## Task:
Add gems for testing applications and configure them

## Change proposed in this pull request:

1. Add Gemfile and Gemfile.lock and add gems such as:

- rspec-rails
- database_cleaner-active_record
- capybara
- shoulda-matchers
- simplecov
- rails-controller-testing

2. Add folder spec/
3. Add configuration of gem database_cleaner-active_record to /spec/support/database_cleaner.rb
4. Add configuration of gem shoulda-matchers to /spec/rails_helper.rb
5. Add configuration of gem simplecov to /spec/spec_helper.rb

2023-08-03 14:21 UTC, TimurShakhlai approved these changes

2023-08-04 07:28 UTC, TsikhanauDzmitry requested changes

2023-08-04 13:52 UTC, TimurShakhlai approved these changes

2023-08-04 14:43 UTC, TsikhanauDzmitry requested changes

2023-08-07 05:52 UTC, TimurShakhlai submitted a review, later dismissed

2023-08-07 08:07 UTC, TsikhanauDzmitry requested changes

2023-08-07 13:06 UTC, The7Fame commented on Gemfile
> +  # Test framework [https://github.com/teamcapybara/capybara]
Исправил

2023-08-07 13:06 UTC, The7Fame commented on Gemfile
> +  # For integration tests [https://github.com/rails/rails-controller-testing]
Исправил

2023-08-07 13:21 UTC, TimurShakhlai approved these changes

2023-08-08 10:40 UTC, TsikhanauDzmitry approved these changes

2023-08-08 11:17 UTC, merged