Add set of rubocop gems
The7Fame/trainee-planner pull request #7
Opened 2023-08-03 13:11 UTC by The7Fame

## Task:
Add gems for linting code

## Change proposed in this pull request:

1. Add Gemfile and Gemfile.lock and add gems such as:

    - rubocop
    - rubocop-rspec
    - rubocop-rails

2. Add folder spec
3. Add configuration of gem rubocop to .rubocop.yml
4. Check functionality configuration of rubocop.yml

2023-08-03 14:24 UTC, TimurShakhlai approved these changes

2023-08-04 07:25 UTC, TsikhanauDzmitry requested changes

2023-08-04 14:19 UTC, TimurShakhlai requested changes
а чего нет коммита для фикс кода рубокопом?

2023-08-04 14:26 UTC, TimurShakhlai approved these changes
увидел коммит, но название странноватое по моему мнению ибо не очень понятно

2023-08-07 05:54 UTC, TimurShakhlai submitted a review, later dismissed

2023-08-07 08:10 UTC, TsikhanauDzmitry requested changes

2023-08-07 08:10 UTC, TsikhanauDzmitry commented on config/initializers/content_security_policy.rb
> +# frozen_string_literal: true
Обычно после `# frozen_string_literal: true` идет пустая строчка

2023-08-07 08:10 UTC, TsikhanauDzmitry commented on config/initializers/inflections.rb
> +# frozen_string_literal: true
Обычно после `# frozen_string_literal: true` идет пустая строчка

2023-08-07 08:10 UTC, TsikhanauDzmitry commented on config/initializers/permissions_policy.rb
> +# frozen_string_literal: true
Обычно после `# frozen_string_literal: true` идет пустая строчка

2023-08-07 08:10 UTC, TsikhanauDzmitry commented on db/seeds.rb
> +# frozen_string_literal: true
Обычно после `# frozen_string_literal: true` идет пустая строчка

2023-08-07 13:05 UTC, The7Fame commented on config/initializers/content_security_policy.rb
> +# frozen_string_literal: true
Исправил

2023-08-07 13:05 UTC, The7Fame commented on config/initializers/inflections.rb
> +# frozen_string_literal: true
Исправил

2023-08-07 13:06 UTC, The7Fame commented on config/initializers/permissions_policy.rb
> +# frozen_string_literal: true
Исправил

2023-08-07 13:06 UTC, The7Fame commented on db/seeds.rb
> +# frozen_string_literal: true
Исправил

2023-08-07 13:23 UTC, TimurShakhlai approved these changes, later dismissed

2023-08-09 01:47 UTC, TimurShakhlai approved these changes

2023-08-09 15:05 UTC, TsikhanauDzmitry approved these changes

2023-08-09 15:19 UTC, merged