Add folder .github/ and add configuration for github actions
The7Fame/trainee-planner pull request #8
Opened 2023-08-08 07:56 UTC by The7Fame

## Task:
Add ci-cd

## Change proposed in this pull request:

1. Add forlder .github/workflows/
2. Make configuration of github actions in file ruby.yml

2023-08-09 15:22 UTC, TimurShakhlai requested changes
Дима сказал, что мы должны добавить CI/CD на каждый push коммита, в любом PR. Т.е. после добавленных изменений в PR должны ранаться проверки

2023-08-09 15:43 UTC, The7Fame commented
> Дима сказал, что мы должны добавить CI/CD на каждый push коммита, в любом PR. Т.е. после добавленных изменений в PR должны ранаться проверки

Напишу здесь , хочешь сказать , что
‘’’
push: 
    branches: **
‘’’

не будет ранить тесты заново или чего-то не так понял ?

2023-08-10 09:54 UTC, TimurShakhlai submitted a review, later dismissed

2023-08-10 12:51 UTC, TsikhanauDzmitry requested changes

2023-08-10 12:51 UTC, TsikhanauDzmitry commented on .github/workflows/ruby.yml
Странное название файла. Как считаешь?

2023-08-10 12:51 UTC, TsikhanauDzmitry commented on .github/workflows/ruby.yml
Может лучше разбить каждую из проверок на отдельные файлы?

2023-08-10 12:51 UTC, TsikhanauDzmitry commented on .github/workflows/ruby.yml
> +      - name: Test DB
Довольно странное название для команды: `run: bundle exec rspec spec`. Как считаешь?

2023-08-10 12:51 UTC, TsikhanauDzmitry commented on Gemfile
> +gem 'rails', '~> 7.0.6'
Почему рельсы не в начале гем-файла? Выглядит странно... Почему вообще все гемы изменили свой порядок?

2023-08-10 12:51 UTC, TsikhanauDzmitry commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my/locales/*.{rb,yml}')]
Интересно, а зачем метод `join` остался?

2023-08-10 13:01 UTC, The7Fame commented on .github/workflows/ruby.yml
Соглашусь

2023-08-10 13:02 UTC, The7Fame commented on .github/workflows/ruby.yml
Да, хорошая идея. Как раз будут понятные названия файлом.

2023-08-10 13:03 UTC, The7Fame commented on .github/workflows/ruby.yml
> +      - name: Test DB
Скорее длинная команда, можно сократить до `rspec spec`.

2023-08-10 13:05 UTC, The7Fame commented on Gemfile
> +gem 'rails', '~> 7.0.6'
Тут уже моё баловство, решил gem'ы в алфавитном порядке расставить.

2023-08-10 13:30 UTC, The7Fame commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my/locales/*.{rb,yml}')]
Для того, чтобы объединить root_path  и указанные путь, чтобы в последующем найти файлы локалей.

2023-08-10 13:49 UTC, TimurShakhlai submitted a review, later dismissed

2023-08-11 07:36 UTC, TimurShakhlai approved these changes

2023-08-11 10:48 UTC, TsikhanauDzmitry approved these changes

2023-08-11 11:50 UTC, merged