Add description of the project to README.md
The7Fame/trainee-planner pull request #9
Opened 2023-08-08 10:01 UTC by The7Fame

## Task:
Add description of the project to README.md

## Change proposed in this pull request:

1. Add functionality about the project
2. Add how to run app 
3. Add gem dotenv-rails
4. Сhange the database.yml file

2023-08-09 07:37 UTC, TimurShakhlai approved these changes, later dismissed

2023-08-09 15:44 UTC, TsikhanauDzmitry requested changes

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +- password: <%= ENV.fetch("POSTGRES_PASSWORD") { <password_of_postgres_user> } %>
Не думаю, что это безопасный вариант. Может лучше сделать какую-нибудь настройку env файла? Как считаешь?

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +```
А разве это все, что нужно? Не вижу допустим установки гемов...

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +```
Этого точно достаточно для запуска. Никакого имейджа билдить не надо?

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +- docker-compose
Было бы очень приятно получить ссылочки на ресурсы. Как считаешь?

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +- Rails 7+
А всякие yarn, npm не нужны?

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +4. The user can find events by name and category or use them simultaneously
Это совсем не похоже на описание проекта...

2023-08-09 15:44 UTC, TsikhanauDzmitry commented on README.md
> +# Web application 'Event planner'  for managing to-do list
Думаю, что это больше похоже на краткое описание, чем на название. Как считаешь?

2023-08-10 13:44 UTC, The7Fame commented on README.md
> +- password: <%= ENV.fetch("POSTGRES_PASSWORD") { <password_of_postgres_user> } %>
Добавил .env.template и установил dotenv-rails.

2023-08-10 13:44 UTC, The7Fame commented on README.md
> +```
Добавил установку gem'ов.

2023-08-10 13:54 UTC, The7Fame commented on README.md
> +```
Да, этого достаточно. Так как сам образ приложения билдится в docker-compose.
- up - запускает контейнеры
- -d - запускает контейнеры в фоновом режиме
- --build - строит или перестраивает образы, если в нём были изменения

2023-08-10 13:54 UTC, The7Fame commented on README.md
> +- docker-compose
Соглашусь, добавил.

2023-08-10 13:54 UTC, The7Fame commented on README.md
> +- Rails 7+
Нужен nodejs, добавил.

2023-08-10 13:59 UTC, The7Fame commented on README.md
> +# Web application 'Event planner'  for managing to-do list
Здесь тогда укорочу запись до ` Web application 'Event planner'`, чтобы было просто название проекта.

2023-08-10 17:53 UTC, The7Fame commented on README.md
> +4. The user can find events by name and category or use them simultaneously
Исправил

2023-08-11 01:04 UTC, TimurShakhlai approved these changes, later dismissed

2023-08-11 10:48 UTC, TimurShakhlai submitted a review, later dismissed

2023-08-11 14:54 UTC, TimurShakhlai approved these changes, later dismissed

2023-08-14 04:24 UTC, TimurShakhlai approved these changes, later dismissed

2023-08-14 11:07 UTC, TsikhanauDzmitry requested changes

2023-08-14 11:07 UTC, TsikhanauDzmitry commented on .env.template
> +# If your wanna start the app with docker-compose
Не думаю, что `wanna` - технический язык...

2023-08-14 11:07 UTC, TsikhanauDzmitry commented on .env.template
> +# If your wanna start the app with docker-compose
Не думаю, что `wanna` - технический язык...

2023-08-14 11:56 UTC, The7Fame commented on .env.template
> +# If your wanna start the app with docker-compose
Исправил

2023-08-14 11:56 UTC, The7Fame commented on .env.template
> +# If your wanna start the app with docker-compose
Исправил

2023-08-15 06:47 UTC, TimurShakhlai approved these changes

2023-08-15 07:23 UTC, TsikhanauDzmitry approved these changes

2023-08-15 07:34 UTC, merged